// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// AssetServiceCreateActionForAssetReader is a Reader for the AssetServiceCreateActionForAsset structure.
type AssetServiceCreateActionForAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetServiceCreateActionForAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetServiceCreateActionForAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAssetServiceCreateActionForAssetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAssetServiceCreateActionForAssetOK creates a AssetServiceCreateActionForAssetOK with default headers values
func NewAssetServiceCreateActionForAssetOK() *AssetServiceCreateActionForAssetOK {
	return &AssetServiceCreateActionForAssetOK{}
}

/* AssetServiceCreateActionForAssetOK describes a response with status code 200, with default header values.

A successful response.
*/
type AssetServiceCreateActionForAssetOK struct {
	Payload int32
}

func (o *AssetServiceCreateActionForAssetOK) Error() string {
	return fmt.Sprintf("[POST /api/assets/create_action][%d] assetServiceCreateActionForAssetOK  %+v", 200, o.Payload)
}
func (o *AssetServiceCreateActionForAssetOK) GetPayload() int32 {
	return o.Payload
}

func (o *AssetServiceCreateActionForAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetServiceCreateActionForAssetDefault creates a AssetServiceCreateActionForAssetDefault with default headers values
func NewAssetServiceCreateActionForAssetDefault(code int) *AssetServiceCreateActionForAssetDefault {
	return &AssetServiceCreateActionForAssetDefault{
		_statusCode: code,
	}
}

/* AssetServiceCreateActionForAssetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AssetServiceCreateActionForAssetDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the asset service create action for asset default response
func (o *AssetServiceCreateActionForAssetDefault) Code() int {
	return o._statusCode
}

func (o *AssetServiceCreateActionForAssetDefault) Error() string {
	return fmt.Sprintf("[POST /api/assets/create_action][%d] AssetService_CreateActionForAsset default  %+v", o._statusCode, o.Payload)
}
func (o *AssetServiceCreateActionForAssetDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AssetServiceCreateActionForAssetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
