// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewAssetServiceCopyAssetParams creates a new AssetServiceCopyAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetServiceCopyAssetParams() *AssetServiceCopyAssetParams {
	return &AssetServiceCopyAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetServiceCopyAssetParamsWithTimeout creates a new AssetServiceCopyAssetParams object
// with the ability to set a timeout on a request.
func NewAssetServiceCopyAssetParamsWithTimeout(timeout time.Duration) *AssetServiceCopyAssetParams {
	return &AssetServiceCopyAssetParams{
		timeout: timeout,
	}
}

// NewAssetServiceCopyAssetParamsWithContext creates a new AssetServiceCopyAssetParams object
// with the ability to set a context for a request.
func NewAssetServiceCopyAssetParamsWithContext(ctx context.Context) *AssetServiceCopyAssetParams {
	return &AssetServiceCopyAssetParams{
		Context: ctx,
	}
}

// NewAssetServiceCopyAssetParamsWithHTTPClient creates a new AssetServiceCopyAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetServiceCopyAssetParamsWithHTTPClient(client *http.Client) *AssetServiceCopyAssetParams {
	return &AssetServiceCopyAssetParams{
		HTTPClient: client,
	}
}

/* AssetServiceCopyAssetParams contains all the parameters to send to the API endpoint
   for the asset service copy asset operation.

   Typically these are written to a http.Request.
*/
type AssetServiceCopyAssetParams struct {

	// Body.
	Body *models.ConquestAPICopyAssetCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the asset service copy asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetServiceCopyAssetParams) WithDefaults() *AssetServiceCopyAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the asset service copy asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetServiceCopyAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) WithTimeout(timeout time.Duration) *AssetServiceCopyAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) WithContext(ctx context.Context) *AssetServiceCopyAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) WithHTTPClient(client *http.Client) *AssetServiceCopyAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) WithBody(body *models.ConquestAPICopyAssetCommand) *AssetServiceCopyAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the asset service copy asset params
func (o *AssetServiceCopyAssetParams) SetBody(body *models.ConquestAPICopyAssetCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AssetServiceCopyAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
