// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewAssetServiceCreateActionForAssetParams creates a new AssetServiceCreateActionForAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetServiceCreateActionForAssetParams() *AssetServiceCreateActionForAssetParams {
	return &AssetServiceCreateActionForAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetServiceCreateActionForAssetParamsWithTimeout creates a new AssetServiceCreateActionForAssetParams object
// with the ability to set a timeout on a request.
func NewAssetServiceCreateActionForAssetParamsWithTimeout(timeout time.Duration) *AssetServiceCreateActionForAssetParams {
	return &AssetServiceCreateActionForAssetParams{
		timeout: timeout,
	}
}

// NewAssetServiceCreateActionForAssetParamsWithContext creates a new AssetServiceCreateActionForAssetParams object
// with the ability to set a context for a request.
func NewAssetServiceCreateActionForAssetParamsWithContext(ctx context.Context) *AssetServiceCreateActionForAssetParams {
	return &AssetServiceCreateActionForAssetParams{
		Context: ctx,
	}
}

// NewAssetServiceCreateActionForAssetParamsWithHTTPClient creates a new AssetServiceCreateActionForAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetServiceCreateActionForAssetParamsWithHTTPClient(client *http.Client) *AssetServiceCreateActionForAssetParams {
	return &AssetServiceCreateActionForAssetParams{
		HTTPClient: client,
	}
}

/* AssetServiceCreateActionForAssetParams contains all the parameters to send to the API endpoint
   for the asset service create action for asset operation.

   Typically these are written to a http.Request.
*/
type AssetServiceCreateActionForAssetParams struct {

	// Body.
	Body *models.ConquestAPICreateActionForAssetCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the asset service create action for asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetServiceCreateActionForAssetParams) WithDefaults() *AssetServiceCreateActionForAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the asset service create action for asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetServiceCreateActionForAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) WithTimeout(timeout time.Duration) *AssetServiceCreateActionForAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) WithContext(ctx context.Context) *AssetServiceCreateActionForAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) WithHTTPClient(client *http.Client) *AssetServiceCreateActionForAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) WithBody(body *models.ConquestAPICreateActionForAssetCommand) *AssetServiceCreateActionForAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the asset service create action for asset params
func (o *AssetServiceCreateActionForAssetParams) SetBody(body *models.ConquestAPICreateActionForAssetCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AssetServiceCreateActionForAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
