// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// AssetServiceListInspectionsForAssetReader is a Reader for the AssetServiceListInspectionsForAsset structure.
type AssetServiceListInspectionsForAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetServiceListInspectionsForAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetServiceListInspectionsForAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAssetServiceListInspectionsForAssetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAssetServiceListInspectionsForAssetOK creates a AssetServiceListInspectionsForAssetOK with default headers values
func NewAssetServiceListInspectionsForAssetOK() *AssetServiceListInspectionsForAssetOK {
	return &AssetServiceListInspectionsForAssetOK{}
}

/* AssetServiceListInspectionsForAssetOK describes a response with status code 200, with default header values.

A successful response.
*/
type AssetServiceListInspectionsForAssetOK struct {
	Payload *models.ConquestAPIInspectionsForAssetResponse
}

func (o *AssetServiceListInspectionsForAssetOK) Error() string {
	return fmt.Sprintf("[POST /api/assets/list_inspections][%d] assetServiceListInspectionsForAssetOK  %+v", 200, o.Payload)
}
func (o *AssetServiceListInspectionsForAssetOK) GetPayload() *models.ConquestAPIInspectionsForAssetResponse {
	return o.Payload
}

func (o *AssetServiceListInspectionsForAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConquestAPIInspectionsForAssetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetServiceListInspectionsForAssetDefault creates a AssetServiceListInspectionsForAssetDefault with default headers values
func NewAssetServiceListInspectionsForAssetDefault(code int) *AssetServiceListInspectionsForAssetDefault {
	return &AssetServiceListInspectionsForAssetDefault{
		_statusCode: code,
	}
}

/* AssetServiceListInspectionsForAssetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AssetServiceListInspectionsForAssetDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the asset service list inspections for asset default response
func (o *AssetServiceListInspectionsForAssetDefault) Code() int {
	return o._statusCode
}

func (o *AssetServiceListInspectionsForAssetDefault) Error() string {
	return fmt.Sprintf("[POST /api/assets/list_inspections][%d] AssetService_ListInspectionsForAsset default  %+v", o._statusCode, o.Payload)
}
func (o *AssetServiceListInspectionsForAssetDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AssetServiceListInspectionsForAssetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
