// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewCreateDefectForAssetParams creates a new CreateDefectForAssetParams object
// with the default values initialized.
func NewCreateDefectForAssetParams() *CreateDefectForAssetParams {
	var ()
	return &CreateDefectForAssetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDefectForAssetParamsWithTimeout creates a new CreateDefectForAssetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDefectForAssetParamsWithTimeout(timeout time.Duration) *CreateDefectForAssetParams {
	var ()
	return &CreateDefectForAssetParams{

		timeout: timeout,
	}
}

// NewCreateDefectForAssetParamsWithContext creates a new CreateDefectForAssetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDefectForAssetParamsWithContext(ctx context.Context) *CreateDefectForAssetParams {
	var ()
	return &CreateDefectForAssetParams{

		Context: ctx,
	}
}

// NewCreateDefectForAssetParamsWithHTTPClient creates a new CreateDefectForAssetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDefectForAssetParamsWithHTTPClient(client *http.Client) *CreateDefectForAssetParams {
	var ()
	return &CreateDefectForAssetParams{
		HTTPClient: client,
	}
}

/*CreateDefectForAssetParams contains all the parameters to send to the API endpoint
for the create defect for asset operation typically these are written to a http.Request
*/
type CreateDefectForAssetParams struct {

	/*Body*/
	Body *models.ConquestAPICreateDefectForAssetCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create defect for asset params
func (o *CreateDefectForAssetParams) WithTimeout(timeout time.Duration) *CreateDefectForAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create defect for asset params
func (o *CreateDefectForAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create defect for asset params
func (o *CreateDefectForAssetParams) WithContext(ctx context.Context) *CreateDefectForAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create defect for asset params
func (o *CreateDefectForAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create defect for asset params
func (o *CreateDefectForAssetParams) WithHTTPClient(client *http.Client) *CreateDefectForAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create defect for asset params
func (o *CreateDefectForAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create defect for asset params
func (o *CreateDefectForAssetParams) WithBody(body *models.ConquestAPICreateDefectForAssetCommand) *CreateDefectForAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create defect for asset params
func (o *CreateDefectForAssetParams) SetBody(body *models.ConquestAPICreateDefectForAssetCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDefectForAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
