// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewDeleteAssetParams creates a new DeleteAssetParams object
// with the default values initialized.
func NewDeleteAssetParams() *DeleteAssetParams {
	var ()
	return &DeleteAssetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAssetParamsWithTimeout creates a new DeleteAssetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAssetParamsWithTimeout(timeout time.Duration) *DeleteAssetParams {
	var ()
	return &DeleteAssetParams{

		timeout: timeout,
	}
}

// NewDeleteAssetParamsWithContext creates a new DeleteAssetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAssetParamsWithContext(ctx context.Context) *DeleteAssetParams {
	var ()
	return &DeleteAssetParams{

		Context: ctx,
	}
}

// NewDeleteAssetParamsWithHTTPClient creates a new DeleteAssetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAssetParamsWithHTTPClient(client *http.Client) *DeleteAssetParams {
	var ()
	return &DeleteAssetParams{
		HTTPClient: client,
	}
}

/*DeleteAssetParams contains all the parameters to send to the API endpoint
for the delete asset operation typically these are written to a http.Request
*/
type DeleteAssetParams struct {

	/*Body*/
	Body *models.ConquestAPIDeleteAssetCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete asset params
func (o *DeleteAssetParams) WithTimeout(timeout time.Duration) *DeleteAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete asset params
func (o *DeleteAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete asset params
func (o *DeleteAssetParams) WithContext(ctx context.Context) *DeleteAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete asset params
func (o *DeleteAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete asset params
func (o *DeleteAssetParams) WithHTTPClient(client *http.Client) *DeleteAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete asset params
func (o *DeleteAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete asset params
func (o *DeleteAssetParams) WithBody(body *models.ConquestAPIDeleteAssetCommand) *DeleteAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete asset params
func (o *DeleteAssetParams) SetBody(body *models.ConquestAPIDeleteAssetCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
