// Code generated by go-swagger; DO NOT EDIT.

package asset_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewNewConditionInspectionParams creates a new NewConditionInspectionParams object
// with the default values initialized.
func NewNewConditionInspectionParams() *NewConditionInspectionParams {
	var ()
	return &NewConditionInspectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNewConditionInspectionParamsWithTimeout creates a new NewConditionInspectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNewConditionInspectionParamsWithTimeout(timeout time.Duration) *NewConditionInspectionParams {
	var ()
	return &NewConditionInspectionParams{

		timeout: timeout,
	}
}

// NewNewConditionInspectionParamsWithContext creates a new NewConditionInspectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewNewConditionInspectionParamsWithContext(ctx context.Context) *NewConditionInspectionParams {
	var ()
	return &NewConditionInspectionParams{

		Context: ctx,
	}
}

// NewNewConditionInspectionParamsWithHTTPClient creates a new NewConditionInspectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNewConditionInspectionParamsWithHTTPClient(client *http.Client) *NewConditionInspectionParams {
	var ()
	return &NewConditionInspectionParams{
		HTTPClient: client,
	}
}

/*NewConditionInspectionParams contains all the parameters to send to the API endpoint
for the new condition inspection operation typically these are written to a http.Request
*/
type NewConditionInspectionParams struct {

	/*Body*/
	Body *models.ConquestAPINewConditionInspectionCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the new condition inspection params
func (o *NewConditionInspectionParams) WithTimeout(timeout time.Duration) *NewConditionInspectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new condition inspection params
func (o *NewConditionInspectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new condition inspection params
func (o *NewConditionInspectionParams) WithContext(ctx context.Context) *NewConditionInspectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new condition inspection params
func (o *NewConditionInspectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new condition inspection params
func (o *NewConditionInspectionParams) WithHTTPClient(client *http.Client) *NewConditionInspectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new condition inspection params
func (o *NewConditionInspectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the new condition inspection params
func (o *NewConditionInspectionParams) WithBody(body *models.ConquestAPINewConditionInspectionCommand) *NewConditionInspectionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the new condition inspection params
func (o *NewConditionInspectionParams) SetBody(body *models.ConquestAPINewConditionInspectionCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NewConditionInspectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
