// Code generated by go-swagger; DO NOT EDIT.

package action_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// ActionServiceReverseActionCompletionReader is a Reader for the ActionServiceReverseActionCompletion structure.
type ActionServiceReverseActionCompletionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActionServiceReverseActionCompletionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActionServiceReverseActionCompletionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActionServiceReverseActionCompletionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActionServiceReverseActionCompletionOK creates a ActionServiceReverseActionCompletionOK with default headers values
func NewActionServiceReverseActionCompletionOK() *ActionServiceReverseActionCompletionOK {
	return &ActionServiceReverseActionCompletionOK{}
}

/* ActionServiceReverseActionCompletionOK describes a response with status code 200, with default header values.

A successful response.
*/
type ActionServiceReverseActionCompletionOK struct {
	Payload models.ConquestAPIReverseActionCompletionResult
}

func (o *ActionServiceReverseActionCompletionOK) Error() string {
	return fmt.Sprintf("[POST /api/actions/reverse_action_completion][%d] actionServiceReverseActionCompletionOK  %+v", 200, o.Payload)
}
func (o *ActionServiceReverseActionCompletionOK) GetPayload() models.ConquestAPIReverseActionCompletionResult {
	return o.Payload
}

func (o *ActionServiceReverseActionCompletionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActionServiceReverseActionCompletionDefault creates a ActionServiceReverseActionCompletionDefault with default headers values
func NewActionServiceReverseActionCompletionDefault(code int) *ActionServiceReverseActionCompletionDefault {
	return &ActionServiceReverseActionCompletionDefault{
		_statusCode: code,
	}
}

/* ActionServiceReverseActionCompletionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActionServiceReverseActionCompletionDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the action service reverse action completion default response
func (o *ActionServiceReverseActionCompletionDefault) Code() int {
	return o._statusCode
}

func (o *ActionServiceReverseActionCompletionDefault) Error() string {
	return fmt.Sprintf("[POST /api/actions/reverse_action_completion][%d] ActionService_ReverseActionCompletion default  %+v", o._statusCode, o.Payload)
}
func (o *ActionServiceReverseActionCompletionDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ActionServiceReverseActionCompletionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
