// Code generated by go-swagger; DO NOT EDIT.

package action_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// ActionServiceMoveActionReader is a Reader for the ActionServiceMoveAction structure.
type ActionServiceMoveActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActionServiceMoveActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActionServiceMoveActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActionServiceMoveActionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActionServiceMoveActionOK creates a ActionServiceMoveActionOK with default headers values
func NewActionServiceMoveActionOK() *ActionServiceMoveActionOK {
	return &ActionServiceMoveActionOK{}
}

/* ActionServiceMoveActionOK describes a response with status code 200, with default header values.

A successful response.
*/
type ActionServiceMoveActionOK struct {
	Payload interface{}
}

func (o *ActionServiceMoveActionOK) Error() string {
	return fmt.Sprintf("[POST /api/actions/move_action][%d] actionServiceMoveActionOK  %+v", 200, o.Payload)
}
func (o *ActionServiceMoveActionOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ActionServiceMoveActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActionServiceMoveActionDefault creates a ActionServiceMoveActionDefault with default headers values
func NewActionServiceMoveActionDefault(code int) *ActionServiceMoveActionDefault {
	return &ActionServiceMoveActionDefault{
		_statusCode: code,
	}
}

/* ActionServiceMoveActionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActionServiceMoveActionDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the action service move action default response
func (o *ActionServiceMoveActionDefault) Code() int {
	return o._statusCode
}

func (o *ActionServiceMoveActionDefault) Error() string {
	return fmt.Sprintf("[POST /api/actions/move_action][%d] ActionService_MoveAction default  %+v", o._statusCode, o.Payload)
}
func (o *ActionServiceMoveActionDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ActionServiceMoveActionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
