// Code generated by go-swagger; DO NOT EDIT.

package action_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewActionServiceMoveActionParams creates a new ActionServiceMoveActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewActionServiceMoveActionParams() *ActionServiceMoveActionParams {
	return &ActionServiceMoveActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewActionServiceMoveActionParamsWithTimeout creates a new ActionServiceMoveActionParams object
// with the ability to set a timeout on a request.
func NewActionServiceMoveActionParamsWithTimeout(timeout time.Duration) *ActionServiceMoveActionParams {
	return &ActionServiceMoveActionParams{
		timeout: timeout,
	}
}

// NewActionServiceMoveActionParamsWithContext creates a new ActionServiceMoveActionParams object
// with the ability to set a context for a request.
func NewActionServiceMoveActionParamsWithContext(ctx context.Context) *ActionServiceMoveActionParams {
	return &ActionServiceMoveActionParams{
		Context: ctx,
	}
}

// NewActionServiceMoveActionParamsWithHTTPClient creates a new ActionServiceMoveActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewActionServiceMoveActionParamsWithHTTPClient(client *http.Client) *ActionServiceMoveActionParams {
	return &ActionServiceMoveActionParams{
		HTTPClient: client,
	}
}

/* ActionServiceMoveActionParams contains all the parameters to send to the API endpoint
   for the action service move action operation.

   Typically these are written to a http.Request.
*/
type ActionServiceMoveActionParams struct {

	// Body.
	Body *models.ConquestAPIMoveActionCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the action service move action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActionServiceMoveActionParams) WithDefaults() *ActionServiceMoveActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the action service move action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActionServiceMoveActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the action service move action params
func (o *ActionServiceMoveActionParams) WithTimeout(timeout time.Duration) *ActionServiceMoveActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the action service move action params
func (o *ActionServiceMoveActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the action service move action params
func (o *ActionServiceMoveActionParams) WithContext(ctx context.Context) *ActionServiceMoveActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the action service move action params
func (o *ActionServiceMoveActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the action service move action params
func (o *ActionServiceMoveActionParams) WithHTTPClient(client *http.Client) *ActionServiceMoveActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the action service move action params
func (o *ActionServiceMoveActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the action service move action params
func (o *ActionServiceMoveActionParams) WithBody(body *models.ConquestAPIMoveActionCommand) *ActionServiceMoveActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the action service move action params
func (o *ActionServiceMoveActionParams) SetBody(body *models.ConquestAPIMoveActionCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ActionServiceMoveActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
