// Code generated by go-swagger; DO NOT EDIT.

package action_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// UpdateActionReader is a Reader for the UpdateAction structure.
type UpdateActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateActionOK creates a UpdateActionOK with default headers values
func NewUpdateActionOK() *UpdateActionOK {
	return &UpdateActionOK{}
}

/*UpdateActionOK handles this case with default header values.

A successful response.
*/
type UpdateActionOK struct {
	Payload *models.ConquestAPIChangeSetResult
}

func (o *UpdateActionOK) Error() string {
	return fmt.Sprintf("[POST /api/actions/update_action][%d] updateActionOK  %+v", 200, o.Payload)
}

func (o *UpdateActionOK) GetPayload() *models.ConquestAPIChangeSetResult {
	return o.Payload
}

func (o *UpdateActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConquestAPIChangeSetResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
