// Code generated by go-swagger; DO NOT EDIT.

package request_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRequestReader is a Reader for the CreateRequest structure.
type CreateRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateRequestOK creates a CreateRequestOK with default headers values
func NewCreateRequestOK() *CreateRequestOK {
	return &CreateRequestOK{}
}

/*CreateRequestOK handles this case with default header values.

A successful response.
*/
type CreateRequestOK struct {
	Payload int32
}

func (o *CreateRequestOK) Error() string {
	return fmt.Sprintf("[POST /api/requests/create_request][%d] createRequestOK  %+v", 200, o.Payload)
}

func (o *CreateRequestOK) GetPayload() int32 {
	return o.Payload
}

func (o *CreateRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
