// Code generated by go-swagger; DO NOT EDIT.

package request_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewDeleteRequestParams creates a new DeleteRequestParams object
// with the default values initialized.
func NewDeleteRequestParams() *DeleteRequestParams {
	var ()
	return &DeleteRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRequestParamsWithTimeout creates a new DeleteRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRequestParamsWithTimeout(timeout time.Duration) *DeleteRequestParams {
	var ()
	return &DeleteRequestParams{

		timeout: timeout,
	}
}

// NewDeleteRequestParamsWithContext creates a new DeleteRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRequestParamsWithContext(ctx context.Context) *DeleteRequestParams {
	var ()
	return &DeleteRequestParams{

		Context: ctx,
	}
}

// NewDeleteRequestParamsWithHTTPClient creates a new DeleteRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRequestParamsWithHTTPClient(client *http.Client) *DeleteRequestParams {
	var ()
	return &DeleteRequestParams{
		HTTPClient: client,
	}
}

/*DeleteRequestParams contains all the parameters to send to the API endpoint
for the delete request operation typically these are written to a http.Request
*/
type DeleteRequestParams struct {

	/*Body*/
	Body *models.ConquestAPIDeleteRequestCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete request params
func (o *DeleteRequestParams) WithTimeout(timeout time.Duration) *DeleteRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete request params
func (o *DeleteRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete request params
func (o *DeleteRequestParams) WithContext(ctx context.Context) *DeleteRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete request params
func (o *DeleteRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete request params
func (o *DeleteRequestParams) WithHTTPClient(client *http.Client) *DeleteRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete request params
func (o *DeleteRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete request params
func (o *DeleteRequestParams) WithBody(body *models.ConquestAPIDeleteRequestCommand) *DeleteRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete request params
func (o *DeleteRequestParams) SetBody(body *models.ConquestAPIDeleteRequestCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
