// Code generated by go-swagger; DO NOT EDIT.

package request_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRequestParams creates a new GetRequestParams object
// with the default values initialized.
func NewGetRequestParams() *GetRequestParams {
	var ()
	return &GetRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRequestParamsWithTimeout creates a new GetRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRequestParamsWithTimeout(timeout time.Duration) *GetRequestParams {
	var ()
	return &GetRequestParams{

		timeout: timeout,
	}
}

// NewGetRequestParamsWithContext creates a new GetRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRequestParamsWithContext(ctx context.Context) *GetRequestParams {
	var ()
	return &GetRequestParams{

		Context: ctx,
	}
}

// NewGetRequestParamsWithHTTPClient creates a new GetRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRequestParamsWithHTTPClient(client *http.Client) *GetRequestParams {
	var ()
	return &GetRequestParams{
		HTTPClient: client,
	}
}

/*GetRequestParams contains all the parameters to send to the API endpoint
for the get request operation typically these are written to a http.Request
*/
type GetRequestParams struct {

	/*Value
	  The int32 value.

	*/
	Value int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get request params
func (o *GetRequestParams) WithTimeout(timeout time.Duration) *GetRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get request params
func (o *GetRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get request params
func (o *GetRequestParams) WithContext(ctx context.Context) *GetRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get request params
func (o *GetRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get request params
func (o *GetRequestParams) WithHTTPClient(client *http.Client) *GetRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get request params
func (o *GetRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValue adds the value to the get request params
func (o *GetRequestParams) WithValue(value int32) *GetRequestParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the get request params
func (o *GetRequestParams) SetValue(value int32) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *GetRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param value
	if err := r.SetPathParam("value", swag.FormatInt32(o.Value)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
