// Code generated by go-swagger; DO NOT EDIT.

package request_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewUpdateRequestParams creates a new UpdateRequestParams object
// with the default values initialized.
func NewUpdateRequestParams() *UpdateRequestParams {
	var ()
	return &UpdateRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRequestParamsWithTimeout creates a new UpdateRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRequestParamsWithTimeout(timeout time.Duration) *UpdateRequestParams {
	var ()
	return &UpdateRequestParams{

		timeout: timeout,
	}
}

// NewUpdateRequestParamsWithContext creates a new UpdateRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRequestParamsWithContext(ctx context.Context) *UpdateRequestParams {
	var ()
	return &UpdateRequestParams{

		Context: ctx,
	}
}

// NewUpdateRequestParamsWithHTTPClient creates a new UpdateRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRequestParamsWithHTTPClient(client *http.Client) *UpdateRequestParams {
	var ()
	return &UpdateRequestParams{
		HTTPClient: client,
	}
}

/*UpdateRequestParams contains all the parameters to send to the API endpoint
for the update request operation typically these are written to a http.Request
*/
type UpdateRequestParams struct {

	/*Body*/
	Body *models.ConquestAPIRequestRecordChangeSet

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update request params
func (o *UpdateRequestParams) WithTimeout(timeout time.Duration) *UpdateRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update request params
func (o *UpdateRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update request params
func (o *UpdateRequestParams) WithContext(ctx context.Context) *UpdateRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update request params
func (o *UpdateRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update request params
func (o *UpdateRequestParams) WithHTTPClient(client *http.Client) *UpdateRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update request params
func (o *UpdateRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update request params
func (o *UpdateRequestParams) WithBody(body *models.ConquestAPIRequestRecordChangeSet) *UpdateRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update request params
func (o *UpdateRequestParams) SetBody(body *models.ConquestAPIRequestRecordChangeSet) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
