// Code generated by go-swagger; DO NOT EDIT.

package view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// ListHierarchyNodesReader is a Reader for the ListHierarchyNodes structure.
type ListHierarchyNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListHierarchyNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListHierarchyNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListHierarchyNodesOK creates a ListHierarchyNodesOK with default headers values
func NewListHierarchyNodesOK() *ListHierarchyNodesOK {
	return &ListHierarchyNodesOK{}
}

/*ListHierarchyNodesOK handles this case with default header values.

A successful response.
*/
type ListHierarchyNodesOK struct {
	Payload *models.ConquestAPIObjectHeadersResult
}

func (o *ListHierarchyNodesOK) Error() string {
	return fmt.Sprintf("[POST /api/list_hierarchy_nodes][%d] listHierarchyNodesOK  %+v", 200, o.Payload)
}

func (o *ListHierarchyNodesOK) GetPayload() *models.ConquestAPIObjectHeadersResult {
	return o.Payload
}

func (o *ListHierarchyNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConquestAPIObjectHeadersResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
