// Code generated by go-swagger; DO NOT EDIT.

package view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new view service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for view service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ViewServiceFind(params *ViewServiceFindParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceFindOK, error)

	ViewServiceListFilters(params *ViewServiceListFiltersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceListFiltersOK, error)

	ViewServiceListHierarchyNodes(params *ViewServiceListHierarchyNodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceListHierarchyNodesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ViewServiceFind finds will select all the provided field names for a given context
*/
func (a *Client) ViewServiceFind(params *ViewServiceFindParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceFindOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewViewServiceFindParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ViewService_Find",
		Method:             "POST",
		PathPattern:        "/api/find",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ViewServiceFindReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ViewServiceFindOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ViewServiceFindDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ViewServiceListFilters view service list filters API
*/
func (a *Client) ViewServiceListFilters(params *ViewServiceListFiltersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceListFiltersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewViewServiceListFiltersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ViewService_ListFilters",
		Method:             "POST",
		PathPattern:        "/api/list_filters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ViewServiceListFiltersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ViewServiceListFiltersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ViewServiceListFiltersDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ViewServiceListHierarchyNodes lists hierarchy nodes returns the target hierarchy node and a list of related hierarchy nodes as requested in the query

  A hierarchy object is an object whose ObjectType and parents ObjectType are the same.
*/
func (a *Client) ViewServiceListHierarchyNodes(params *ViewServiceListHierarchyNodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ViewServiceListHierarchyNodesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewViewServiceListHierarchyNodesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ViewService_ListHierarchyNodes",
		Method:             "POST",
		PathPattern:        "/api/list_hierarchy_nodes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ViewServiceListHierarchyNodesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ViewServiceListHierarchyNodesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ViewServiceListHierarchyNodesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
