// Code generated by go-swagger; DO NOT EDIT.

package document_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// DocumentServiceChangeDocumentContentReader is a Reader for the DocumentServiceChangeDocumentContent structure.
type DocumentServiceChangeDocumentContentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentServiceChangeDocumentContentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDocumentServiceChangeDocumentContentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDocumentServiceChangeDocumentContentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDocumentServiceChangeDocumentContentOK creates a DocumentServiceChangeDocumentContentOK with default headers values
func NewDocumentServiceChangeDocumentContentOK() *DocumentServiceChangeDocumentContentOK {
	return &DocumentServiceChangeDocumentContentOK{}
}

/* DocumentServiceChangeDocumentContentOK describes a response with status code 200, with default header values.

A successful response.
*/
type DocumentServiceChangeDocumentContentOK struct {
	Payload *models.ConquestAPIAddDocumentResult
}

func (o *DocumentServiceChangeDocumentContentOK) Error() string {
	return fmt.Sprintf("[POST /api/documents/change_document_content][%d] documentServiceChangeDocumentContentOK  %+v", 200, o.Payload)
}
func (o *DocumentServiceChangeDocumentContentOK) GetPayload() *models.ConquestAPIAddDocumentResult {
	return o.Payload
}

func (o *DocumentServiceChangeDocumentContentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConquestAPIAddDocumentResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDocumentServiceChangeDocumentContentDefault creates a DocumentServiceChangeDocumentContentDefault with default headers values
func NewDocumentServiceChangeDocumentContentDefault(code int) *DocumentServiceChangeDocumentContentDefault {
	return &DocumentServiceChangeDocumentContentDefault{
		_statusCode: code,
	}
}

/* DocumentServiceChangeDocumentContentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DocumentServiceChangeDocumentContentDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the document service change document content default response
func (o *DocumentServiceChangeDocumentContentDefault) Code() int {
	return o._statusCode
}

func (o *DocumentServiceChangeDocumentContentDefault) Error() string {
	return fmt.Sprintf("[POST /api/documents/change_document_content][%d] DocumentService_ChangeDocumentContent default  %+v", o._statusCode, o.Payload)
}
func (o *DocumentServiceChangeDocumentContentDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DocumentServiceChangeDocumentContentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
