// Code generated by go-swagger; DO NOT EDIT.

package document_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewDocumentServiceChangeDocumentContentParams creates a new DocumentServiceChangeDocumentContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDocumentServiceChangeDocumentContentParams() *DocumentServiceChangeDocumentContentParams {
	return &DocumentServiceChangeDocumentContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDocumentServiceChangeDocumentContentParamsWithTimeout creates a new DocumentServiceChangeDocumentContentParams object
// with the ability to set a timeout on a request.
func NewDocumentServiceChangeDocumentContentParamsWithTimeout(timeout time.Duration) *DocumentServiceChangeDocumentContentParams {
	return &DocumentServiceChangeDocumentContentParams{
		timeout: timeout,
	}
}

// NewDocumentServiceChangeDocumentContentParamsWithContext creates a new DocumentServiceChangeDocumentContentParams object
// with the ability to set a context for a request.
func NewDocumentServiceChangeDocumentContentParamsWithContext(ctx context.Context) *DocumentServiceChangeDocumentContentParams {
	return &DocumentServiceChangeDocumentContentParams{
		Context: ctx,
	}
}

// NewDocumentServiceChangeDocumentContentParamsWithHTTPClient creates a new DocumentServiceChangeDocumentContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewDocumentServiceChangeDocumentContentParamsWithHTTPClient(client *http.Client) *DocumentServiceChangeDocumentContentParams {
	return &DocumentServiceChangeDocumentContentParams{
		HTTPClient: client,
	}
}

/* DocumentServiceChangeDocumentContentParams contains all the parameters to send to the API endpoint
   for the document service change document content operation.

   Typically these are written to a http.Request.
*/
type DocumentServiceChangeDocumentContentParams struct {

	// Body.
	Body *models.ConquestAPIChangeDocumentContentCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the document service change document content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentServiceChangeDocumentContentParams) WithDefaults() *DocumentServiceChangeDocumentContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the document service change document content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentServiceChangeDocumentContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) WithTimeout(timeout time.Duration) *DocumentServiceChangeDocumentContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) WithContext(ctx context.Context) *DocumentServiceChangeDocumentContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) WithHTTPClient(client *http.Client) *DocumentServiceChangeDocumentContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) WithBody(body *models.ConquestAPIChangeDocumentContentCommand) *DocumentServiceChangeDocumentContentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the document service change document content params
func (o *DocumentServiceChangeDocumentContentParams) SetBody(body *models.ConquestAPIChangeDocumentContentCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DocumentServiceChangeDocumentContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
