// Code generated by go-swagger; DO NOT EDIT.

package document_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RemoveDocumentReader is a Reader for the RemoveDocument structure.
type RemoveDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveDocumentOK creates a RemoveDocumentOK with default headers values
func NewRemoveDocumentOK() *RemoveDocumentOK {
	return &RemoveDocumentOK{}
}

/*RemoveDocumentOK handles this case with default header values.

A successful response.
*/
type RemoveDocumentOK struct {
	Payload interface{}
}

func (o *RemoveDocumentOK) Error() string {
	return fmt.Sprintf("[POST /api/documents/remove_document][%d] removeDocumentOK  %+v", 200, o.Payload)
}

func (o *RemoveDocumentOK) GetPayload() interface{} {
	return o.Payload
}

func (o *RemoveDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
