// Code generated by go-swagger; DO NOT EDIT.

package asset_inspection_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// AssetInspectionServiceCreateAssetInspectionReader is a Reader for the AssetInspectionServiceCreateAssetInspection structure.
type AssetInspectionServiceCreateAssetInspectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetInspectionServiceCreateAssetInspectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetInspectionServiceCreateAssetInspectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAssetInspectionServiceCreateAssetInspectionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAssetInspectionServiceCreateAssetInspectionOK creates a AssetInspectionServiceCreateAssetInspectionOK with default headers values
func NewAssetInspectionServiceCreateAssetInspectionOK() *AssetInspectionServiceCreateAssetInspectionOK {
	return &AssetInspectionServiceCreateAssetInspectionOK{}
}

/* AssetInspectionServiceCreateAssetInspectionOK describes a response with status code 200, with default header values.

A successful response.
*/
type AssetInspectionServiceCreateAssetInspectionOK struct {
	Payload int32
}

func (o *AssetInspectionServiceCreateAssetInspectionOK) Error() string {
	return fmt.Sprintf("[POST /api/asset_inspections/create_asset_inspection][%d] assetInspectionServiceCreateAssetInspectionOK  %+v", 200, o.Payload)
}
func (o *AssetInspectionServiceCreateAssetInspectionOK) GetPayload() int32 {
	return o.Payload
}

func (o *AssetInspectionServiceCreateAssetInspectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetInspectionServiceCreateAssetInspectionDefault creates a AssetInspectionServiceCreateAssetInspectionDefault with default headers values
func NewAssetInspectionServiceCreateAssetInspectionDefault(code int) *AssetInspectionServiceCreateAssetInspectionDefault {
	return &AssetInspectionServiceCreateAssetInspectionDefault{
		_statusCode: code,
	}
}

/* AssetInspectionServiceCreateAssetInspectionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AssetInspectionServiceCreateAssetInspectionDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the asset inspection service create asset inspection default response
func (o *AssetInspectionServiceCreateAssetInspectionDefault) Code() int {
	return o._statusCode
}

func (o *AssetInspectionServiceCreateAssetInspectionDefault) Error() string {
	return fmt.Sprintf("[POST /api/asset_inspections/create_asset_inspection][%d] AssetInspectionService_CreateAssetInspection default  %+v", o._statusCode, o.Payload)
}
func (o *AssetInspectionServiceCreateAssetInspectionDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AssetInspectionServiceCreateAssetInspectionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
