// Code generated by go-swagger; DO NOT EDIT.

package knowledge_base_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewKnowledgeBaseServiceListViewFieldsParams creates a new KnowledgeBaseServiceListViewFieldsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKnowledgeBaseServiceListViewFieldsParams() *KnowledgeBaseServiceListViewFieldsParams {
	return &KnowledgeBaseServiceListViewFieldsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKnowledgeBaseServiceListViewFieldsParamsWithTimeout creates a new KnowledgeBaseServiceListViewFieldsParams object
// with the ability to set a timeout on a request.
func NewKnowledgeBaseServiceListViewFieldsParamsWithTimeout(timeout time.Duration) *KnowledgeBaseServiceListViewFieldsParams {
	return &KnowledgeBaseServiceListViewFieldsParams{
		timeout: timeout,
	}
}

// NewKnowledgeBaseServiceListViewFieldsParamsWithContext creates a new KnowledgeBaseServiceListViewFieldsParams object
// with the ability to set a context for a request.
func NewKnowledgeBaseServiceListViewFieldsParamsWithContext(ctx context.Context) *KnowledgeBaseServiceListViewFieldsParams {
	return &KnowledgeBaseServiceListViewFieldsParams{
		Context: ctx,
	}
}

// NewKnowledgeBaseServiceListViewFieldsParamsWithHTTPClient creates a new KnowledgeBaseServiceListViewFieldsParams object
// with the ability to set a custom HTTPClient for a request.
func NewKnowledgeBaseServiceListViewFieldsParamsWithHTTPClient(client *http.Client) *KnowledgeBaseServiceListViewFieldsParams {
	return &KnowledgeBaseServiceListViewFieldsParams{
		HTTPClient: client,
	}
}

/* KnowledgeBaseServiceListViewFieldsParams contains all the parameters to send to the API endpoint
   for the knowledge base service list view fields operation.

   Typically these are written to a http.Request.
*/
type KnowledgeBaseServiceListViewFieldsParams struct {

	// Body.
	Body *models.ConquestAPIListViewFieldsQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the knowledge base service list view fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KnowledgeBaseServiceListViewFieldsParams) WithDefaults() *KnowledgeBaseServiceListViewFieldsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the knowledge base service list view fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KnowledgeBaseServiceListViewFieldsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) WithTimeout(timeout time.Duration) *KnowledgeBaseServiceListViewFieldsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) WithContext(ctx context.Context) *KnowledgeBaseServiceListViewFieldsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) WithHTTPClient(client *http.Client) *KnowledgeBaseServiceListViewFieldsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) WithBody(body *models.ConquestAPIListViewFieldsQuery) *KnowledgeBaseServiceListViewFieldsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the knowledge base service list view fields params
func (o *KnowledgeBaseServiceListViewFieldsParams) SetBody(body *models.ConquestAPIListViewFieldsQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *KnowledgeBaseServiceListViewFieldsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
