// Code generated by go-swagger; DO NOT EDIT.

package knowledge_base_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewKnowledgeBaseServiceListAttributeSetsParams creates a new KnowledgeBaseServiceListAttributeSetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKnowledgeBaseServiceListAttributeSetsParams() *KnowledgeBaseServiceListAttributeSetsParams {
	return &KnowledgeBaseServiceListAttributeSetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKnowledgeBaseServiceListAttributeSetsParamsWithTimeout creates a new KnowledgeBaseServiceListAttributeSetsParams object
// with the ability to set a timeout on a request.
func NewKnowledgeBaseServiceListAttributeSetsParamsWithTimeout(timeout time.Duration) *KnowledgeBaseServiceListAttributeSetsParams {
	return &KnowledgeBaseServiceListAttributeSetsParams{
		timeout: timeout,
	}
}

// NewKnowledgeBaseServiceListAttributeSetsParamsWithContext creates a new KnowledgeBaseServiceListAttributeSetsParams object
// with the ability to set a context for a request.
func NewKnowledgeBaseServiceListAttributeSetsParamsWithContext(ctx context.Context) *KnowledgeBaseServiceListAttributeSetsParams {
	return &KnowledgeBaseServiceListAttributeSetsParams{
		Context: ctx,
	}
}

// NewKnowledgeBaseServiceListAttributeSetsParamsWithHTTPClient creates a new KnowledgeBaseServiceListAttributeSetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewKnowledgeBaseServiceListAttributeSetsParamsWithHTTPClient(client *http.Client) *KnowledgeBaseServiceListAttributeSetsParams {
	return &KnowledgeBaseServiceListAttributeSetsParams{
		HTTPClient: client,
	}
}

/* KnowledgeBaseServiceListAttributeSetsParams contains all the parameters to send to the API endpoint
   for the knowledge base service list attribute sets operation.

   Typically these are written to a http.Request.
*/
type KnowledgeBaseServiceListAttributeSetsParams struct {

	// Body.
	Body *models.ConquestAPIListAttributeSetsQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the knowledge base service list attribute sets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KnowledgeBaseServiceListAttributeSetsParams) WithDefaults() *KnowledgeBaseServiceListAttributeSetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the knowledge base service list attribute sets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KnowledgeBaseServiceListAttributeSetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) WithTimeout(timeout time.Duration) *KnowledgeBaseServiceListAttributeSetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) WithContext(ctx context.Context) *KnowledgeBaseServiceListAttributeSetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) WithHTTPClient(client *http.Client) *KnowledgeBaseServiceListAttributeSetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) WithBody(body *models.ConquestAPIListAttributeSetsQuery) *KnowledgeBaseServiceListAttributeSetsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the knowledge base service list attribute sets params
func (o *KnowledgeBaseServiceListAttributeSetsParams) SetBody(body *models.ConquestAPIListAttributeSetsQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *KnowledgeBaseServiceListAttributeSetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
