// Code generated by go-swagger; DO NOT EDIT.

package knowledge_base_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/apiv2.examples/go-swagger/models"
)

// NewListStandardDefectResponsesParams creates a new ListStandardDefectResponsesParams object
// with the default values initialized.
func NewListStandardDefectResponsesParams() *ListStandardDefectResponsesParams {
	var ()
	return &ListStandardDefectResponsesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListStandardDefectResponsesParamsWithTimeout creates a new ListStandardDefectResponsesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListStandardDefectResponsesParamsWithTimeout(timeout time.Duration) *ListStandardDefectResponsesParams {
	var ()
	return &ListStandardDefectResponsesParams{

		timeout: timeout,
	}
}

// NewListStandardDefectResponsesParamsWithContext creates a new ListStandardDefectResponsesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListStandardDefectResponsesParamsWithContext(ctx context.Context) *ListStandardDefectResponsesParams {
	var ()
	return &ListStandardDefectResponsesParams{

		Context: ctx,
	}
}

// NewListStandardDefectResponsesParamsWithHTTPClient creates a new ListStandardDefectResponsesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListStandardDefectResponsesParamsWithHTTPClient(client *http.Client) *ListStandardDefectResponsesParams {
	var ()
	return &ListStandardDefectResponsesParams{
		HTTPClient: client,
	}
}

/*ListStandardDefectResponsesParams contains all the parameters to send to the API endpoint
for the list standard defect responses operation typically these are written to a http.Request
*/
type ListStandardDefectResponsesParams struct {

	/*Body*/
	Body *models.ConquestAPIListStandardDefectResponsesQuery

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) WithTimeout(timeout time.Duration) *ListStandardDefectResponsesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) WithContext(ctx context.Context) *ListStandardDefectResponsesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) WithHTTPClient(client *http.Client) *ListStandardDefectResponsesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) WithBody(body *models.ConquestAPIListStandardDefectResponsesQuery) *ListStandardDefectResponsesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list standard defect responses params
func (o *ListStandardDefectResponsesParams) SetBody(body *models.ConquestAPIListStandardDefectResponsesQuery) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListStandardDefectResponsesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
