// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIConfigDatabaseConnection conquest api config database connection
//
// swagger:model conquest_api_configDatabaseConnection
type ConquestAPIConfigDatabaseConnection struct {

	// connectionString: (required)
	//   The following properties are supported:
	//   - Username
	//   - Password
	//   - Integrated Security = true or false
	//   - Server
	//   - Database
	//
	// example: "Database=Conquest; Integrated Security=True; Server=.;"
	ConnectionString string `json:"connection_string,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// name: (required)
	//   The name that will appear in the connection list
	Name string `json:"name,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`
}

// Validate validates this conquest api config database connection
func (m *ConquestAPIConfigDatabaseConnection) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIConfigDatabaseConnection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIConfigDatabaseConnection) UnmarshalBinary(b []byte) error {
	var res ConquestAPIConfigDatabaseConnection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
