// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIPredefinedContextCriteria PredefinedContextCriteria is a filter applied to a Context
//
// swagger:model conquest_apiPredefinedContextCriteria
type ConquestAPIPredefinedContextCriteria struct {

	// criteria
	Criteria *ConquestAPICriteria `json:"Criteria,omitempty"`

	// EnabledByDefault specifies whether the filter is applied to a Context is no preference is specified.
	EnabledByDefault bool `json:"EnabledByDefault,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this conquest api predefined context criteria
func (m *ConquestAPIPredefinedContextCriteria) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCriteria(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIPredefinedContextCriteria) validateCriteria(formats strfmt.Registry) error {

	if swag.IsZero(m.Criteria) { // not required
		return nil
	}

	if m.Criteria != nil {
		if err := m.Criteria.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Criteria")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIPredefinedContextCriteria) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIPredefinedContextCriteria) UnmarshalBinary(b []byte) error {
	var res ConquestAPIPredefinedContextCriteria
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
