// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPICreateRequestCommand conquest api create request command
//
// swagger:model conquest_apiCreateRequestCommand
type ConquestAPICreateRequestCommand struct {

	// change set
	ChangeSet *ConquestAPIRequestRecordChangeSet `json:"ChangeSet,omitempty"`
}

// Validate validates this conquest api create request command
func (m *ConquestAPICreateRequestCommand) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangeSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPICreateRequestCommand) validateChangeSet(formats strfmt.Registry) error {
	if swag.IsZero(m.ChangeSet) { // not required
		return nil
	}

	if m.ChangeSet != nil {
		if err := m.ChangeSet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ChangeSet")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ChangeSet")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this conquest api create request command based on the context it is used
func (m *ConquestAPICreateRequestCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChangeSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPICreateRequestCommand) contextValidateChangeSet(ctx context.Context, formats strfmt.Registry) error {

	if m.ChangeSet != nil {
		if err := m.ChangeSet.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ChangeSet")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ChangeSet")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPICreateRequestCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPICreateRequestCommand) UnmarshalBinary(b []byte) error {
	var res ConquestAPICreateRequestCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
