// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIStandardActionRecord conquest api standard action record
//
// swagger:model conquest_apiStandardActionRecord
type ConquestAPIStandardActionRecord struct {

	// action category
	ActionCategory int32 `json:"ActionCategory,omitempty"`

	// action type
	ActionType ConquestAPIActionType `json:"ActionType,omitempty"`

	// request response
	RequestResponse bool `json:"RequestResponse,omitempty"`

	// std action description
	StdActionDescription string `json:"StdActionDescription,omitempty"`
}

// Validate validates this conquest api standard action record
func (m *ConquestAPIStandardActionRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIStandardActionRecord) validateActionType(formats strfmt.Registry) error {

	if swag.IsZero(m.ActionType) { // not required
		return nil
	}

	if err := m.ActionType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ActionType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIStandardActionRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIStandardActionRecord) UnmarshalBinary(b []byte) error {
	var res ConquestAPIStandardActionRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
