// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIAssetRecord AssetRecord is a selection of fields that may be modified directly.
// TODO: Risk, Valuation fields are omitted, they will be introduced later
//
// swagger:model conquest_apiAssetRecord
type ConquestAPIAssetRecord struct {

	// account no
	AccountNo string `json:"AccountNo,omitempty"`

	// actual age
	ActualAge bool `json:"ActualAge,omitempty"`

	// address1
	Address1 string `json:"Address1,omitempty"`

	// address2
	Address2 string `json:"Address2,omitempty"`

	// asset description
	AssetDescription string `json:"AssetDescription,omitempty"`

	// asset notes
	AssetNotes string `json:"AssetNotes,omitempty"`

	// attribute1
	Attribute1 int32 `json:"Attribute1,omitempty"`

	// attribute10
	Attribute10 int32 `json:"Attribute10,omitempty"`

	// attribute2
	Attribute2 int32 `json:"Attribute2,omitempty"`

	// attribute3
	Attribute3 int32 `json:"Attribute3,omitempty"`

	// attribute4
	Attribute4 int32 `json:"Attribute4,omitempty"`

	// attribute5
	Attribute5 int32 `json:"Attribute5,omitempty"`

	// attribute6
	Attribute6 int32 `json:"Attribute6,omitempty"`

	// attribute7
	Attribute7 int32 `json:"Attribute7,omitempty"`

	// attribute8
	Attribute8 int32 `json:"Attribute8,omitempty"`

	// attribute9
	Attribute9 int32 `json:"Attribute9,omitempty"`

	// bar code
	BarCode string `json:"BarCode,omitempty"`

	// business ID
	BusinessID string `json:"BusinessID,omitempty"`

	// condition
	Condition int32 `json:"Condition,omitempty"`

	// condition point
	ConditionPoint float64 `json:"ConditionPoint,omitempty"`

	// DCID is the Deterioration Curve ID
	DCID int32 `json:"DCID,omitempty"`

	// date acquired
	DateAcquired *ConquestAPITimestampValue `json:"DateAcquired,omitempty"`

	// department ID
	DepartmentID int32 `json:"DepartmentID,omitempty"`

	// dimension1
	Dimension1 float64 `json:"Dimension1,omitempty"`

	// dimension2
	Dimension2 float64 `json:"Dimension2,omitempty"`

	// dimension3
	Dimension3 float64 `json:"Dimension3,omitempty"`

	// dimension4
	Dimension4 float64 `json:"Dimension4,omitempty"`

	// dimension5
	Dimension5 float64 `json:"Dimension5,omitempty"`

	// dimension6
	Dimension6 float64 `json:"Dimension6,omitempty"`

	// dimension7
	Dimension7 float64 `json:"Dimension7,omitempty"`

	// dimension8
	Dimension8 float64 `json:"Dimension8,omitempty"`

	// environment1
	Environment1 int32 `json:"Environment1,omitempty"`

	// environment2
	Environment2 int32 `json:"Environment2,omitempty"`

	// environment3
	Environment3 int32 `json:"Environment3,omitempty"`

	// environment4
	Environment4 int32 `json:"Environment4,omitempty"`

	// environment5
	Environment5 int32 `json:"Environment5,omitempty"`

	// environment6
	Environment6 int32 `json:"Environment6,omitempty"`

	// environment7
	Environment7 int32 `json:"Environment7,omitempty"`

	// environment8
	Environment8 int32 `json:"Environment8,omitempty"`

	// expiry
	Expiry *ConquestAPITimestampValue `json:"Expiry,omitempty"`

	// EXPERIMENTAL: Changing the FunctionID is a Key Parameter for a Valuation type.
	// Key Parameter changes may require the Expiry Date to be updated
	FunctionID int32 `json:"FunctionID,omitempty"`

	// geometry data
	GeometryData *ConquestAPIGeometryDataValue `json:"GeometryData,omitempty"`

	// location
	Location string `json:"Location,omitempty"`

	// LocationCoordinates is a pin/point that defaults to the centroid on the Asset's geography object
	LocationCoordinates *ConquestAPIGeographyDataValue `json:"LocationCoordinates,omitempty"`

	// location ID
	LocationID int32 `json:"LocationID,omitempty"`

	// log action
	LogAction int32 `json:"LogAction,omitempty"`

	// log book ID
	LogBookID int32 `json:"LogBookID,omitempty"`

	// man calc cnd
	ManCalcCnd bool `json:"ManCalcCnd,omitempty"`

	// measurement
	Measurement float64 `json:"Measurement,omitempty"`

	// owned by
	OwnedBy int32 `json:"OwnedBy,omitempty"`

	// param1
	Param1 int32 `json:"Param1,omitempty"`

	// param2
	Param2 int32 `json:"Param2,omitempty"`

	// param3
	Param3 int32 `json:"Param3,omitempty"`

	// param4
	Param4 int32 `json:"Param4,omitempty"`

	// param5
	Param5 int32 `json:"Param5,omitempty"`

	// param6
	Param6 int32 `json:"Param6,omitempty"`

	// param7
	Param7 int32 `json:"Param7,omitempty"`

	// param8
	Param8 int32 `json:"Param8,omitempty"`

	// postcode
	Postcode string `json:"Postcode,omitempty"`

	// priority point
	PriorityPoint float64 `json:"PriorityPoint,omitempty"`

	// renew
	Renew bool `json:"Renew,omitempty"`

	// renew by
	RenewBy *ConquestAPITimestampValue `json:"RenewBy,omitempty"`

	// state
	State string `json:"State,omitempty"`

	// suburb
	Suburb string `json:"Suburb,omitempty"`

	// sys user check1
	SysUserCheck1 bool `json:"SysUserCheck1,omitempty"`

	// sys user check2
	SysUserCheck2 bool `json:"SysUserCheck2,omitempty"`

	// sys user date1
	SysUserDate1 *ConquestAPITimestampValue `json:"SysUserDate1,omitempty"`

	// sys user date2
	SysUserDate2 *ConquestAPITimestampValue `json:"SysUserDate2,omitempty"`

	// sys user hierarchy1
	SysUserHierarchy1 int32 `json:"SysUserHierarchy1,omitempty"`

	// sys user hierarchy2
	SysUserHierarchy2 int32 `json:"SysUserHierarchy2,omitempty"`

	// sys user list1
	SysUserList1 int32 `json:"SysUserList1,omitempty"`

	// sys user list2
	SysUserList2 int32 `json:"SysUserList2,omitempty"`

	// sys user list3
	SysUserList3 int32 `json:"SysUserList3,omitempty"`

	// sys user list4
	SysUserList4 int32 `json:"SysUserList4,omitempty"`

	// sys user number1
	SysUserNumber1 float64 `json:"SysUserNumber1,omitempty"`

	// sys user number2
	SysUserNumber2 float64 `json:"SysUserNumber2,omitempty"`

	// sys user text1
	SysUserText1 string `json:"SysUserText1,omitempty"`

	// sys user text2
	SysUserText2 string `json:"SysUserText2,omitempty"`

	// sys user text3
	SysUserText3 string `json:"SysUserText3,omitempty"`

	// sys user text4
	SysUserText4 string `json:"SysUserText4,omitempty"`

	// sys user text5
	SysUserText5 string `json:"SysUserText5,omitempty"`

	// sys user text6
	SysUserText6 string `json:"SysUserText6,omitempty"`

	// sys user text7
	SysUserText7 string `json:"SysUserText7,omitempty"`

	// sys user text8
	SysUserText8 string `json:"SysUserText8,omitempty"`

	// To change the Asset Type for a valuation type, use the ChangeAssetTypeCommand.
	TypeID int32 `json:"TypeID,omitempty"`

	// user check1
	UserCheck1 bool `json:"UserCheck1,omitempty"`

	// user check10
	UserCheck10 bool `json:"UserCheck10,omitempty"`

	// user check11
	UserCheck11 bool `json:"UserCheck11,omitempty"`

	// user check12
	UserCheck12 bool `json:"UserCheck12,omitempty"`

	// user check13
	UserCheck13 bool `json:"UserCheck13,omitempty"`

	// user check14
	UserCheck14 bool `json:"UserCheck14,omitempty"`

	// user check15
	UserCheck15 bool `json:"UserCheck15,omitempty"`

	// user check16
	UserCheck16 bool `json:"UserCheck16,omitempty"`

	// user check17
	UserCheck17 bool `json:"UserCheck17,omitempty"`

	// user check18
	UserCheck18 bool `json:"UserCheck18,omitempty"`

	// user check19
	UserCheck19 bool `json:"UserCheck19,omitempty"`

	// user check2
	UserCheck2 bool `json:"UserCheck2,omitempty"`

	// user check20
	UserCheck20 bool `json:"UserCheck20,omitempty"`

	// user check21
	UserCheck21 bool `json:"UserCheck21,omitempty"`

	// user check22
	UserCheck22 bool `json:"UserCheck22,omitempty"`

	// user check23
	UserCheck23 bool `json:"UserCheck23,omitempty"`

	// user check24
	UserCheck24 bool `json:"UserCheck24,omitempty"`

	// user check25
	UserCheck25 bool `json:"UserCheck25,omitempty"`

	// user check26
	UserCheck26 bool `json:"UserCheck26,omitempty"`

	// user check27
	UserCheck27 bool `json:"UserCheck27,omitempty"`

	// user check28
	UserCheck28 bool `json:"UserCheck28,omitempty"`

	// user check29
	UserCheck29 bool `json:"UserCheck29,omitempty"`

	// user check3
	UserCheck3 bool `json:"UserCheck3,omitempty"`

	// user check30
	UserCheck30 bool `json:"UserCheck30,omitempty"`

	// user check4
	UserCheck4 bool `json:"UserCheck4,omitempty"`

	// user check5
	UserCheck5 bool `json:"UserCheck5,omitempty"`

	// user check6
	UserCheck6 bool `json:"UserCheck6,omitempty"`

	// user check7
	UserCheck7 bool `json:"UserCheck7,omitempty"`

	// user check8
	UserCheck8 bool `json:"UserCheck8,omitempty"`

	// user check9
	UserCheck9 bool `json:"UserCheck9,omitempty"`

	// user date1
	UserDate1 *ConquestAPITimestampValue `json:"UserDate1,omitempty"`

	// user date10
	UserDate10 *ConquestAPITimestampValue `json:"UserDate10,omitempty"`

	// user date11
	UserDate11 *ConquestAPITimestampValue `json:"UserDate11,omitempty"`

	// user date12
	UserDate12 *ConquestAPITimestampValue `json:"UserDate12,omitempty"`

	// user date13
	UserDate13 *ConquestAPITimestampValue `json:"UserDate13,omitempty"`

	// user date14
	UserDate14 *ConquestAPITimestampValue `json:"UserDate14,omitempty"`

	// user date15
	UserDate15 *ConquestAPITimestampValue `json:"UserDate15,omitempty"`

	// user date16
	UserDate16 *ConquestAPITimestampValue `json:"UserDate16,omitempty"`

	// user date17
	UserDate17 *ConquestAPITimestampValue `json:"UserDate17,omitempty"`

	// user date18
	UserDate18 *ConquestAPITimestampValue `json:"UserDate18,omitempty"`

	// user date19
	UserDate19 *ConquestAPITimestampValue `json:"UserDate19,omitempty"`

	// user date2
	UserDate2 *ConquestAPITimestampValue `json:"UserDate2,omitempty"`

	// user date20
	UserDate20 *ConquestAPITimestampValue `json:"UserDate20,omitempty"`

	// user date21
	UserDate21 *ConquestAPITimestampValue `json:"UserDate21,omitempty"`

	// user date22
	UserDate22 *ConquestAPITimestampValue `json:"UserDate22,omitempty"`

	// user date23
	UserDate23 *ConquestAPITimestampValue `json:"UserDate23,omitempty"`

	// user date24
	UserDate24 *ConquestAPITimestampValue `json:"UserDate24,omitempty"`

	// user date25
	UserDate25 *ConquestAPITimestampValue `json:"UserDate25,omitempty"`

	// user date26
	UserDate26 *ConquestAPITimestampValue `json:"UserDate26,omitempty"`

	// user date27
	UserDate27 *ConquestAPITimestampValue `json:"UserDate27,omitempty"`

	// user date28
	UserDate28 *ConquestAPITimestampValue `json:"UserDate28,omitempty"`

	// user date29
	UserDate29 *ConquestAPITimestampValue `json:"UserDate29,omitempty"`

	// user date3
	UserDate3 *ConquestAPITimestampValue `json:"UserDate3,omitempty"`

	// user date30
	UserDate30 *ConquestAPITimestampValue `json:"UserDate30,omitempty"`

	// user date4
	UserDate4 *ConquestAPITimestampValue `json:"UserDate4,omitempty"`

	// user date5
	UserDate5 *ConquestAPITimestampValue `json:"UserDate5,omitempty"`

	// user date6
	UserDate6 *ConquestAPITimestampValue `json:"UserDate6,omitempty"`

	// user date7
	UserDate7 *ConquestAPITimestampValue `json:"UserDate7,omitempty"`

	// user date8
	UserDate8 *ConquestAPITimestampValue `json:"UserDate8,omitempty"`

	// user date9
	UserDate9 *ConquestAPITimestampValue `json:"UserDate9,omitempty"`

	// user list1
	UserList1 int32 `json:"UserList1,omitempty"`

	// user list10
	UserList10 int32 `json:"UserList10,omitempty"`

	// user list11
	UserList11 int32 `json:"UserList11,omitempty"`

	// user list12
	UserList12 int32 `json:"UserList12,omitempty"`

	// user list13
	UserList13 int32 `json:"UserList13,omitempty"`

	// user list14
	UserList14 int32 `json:"UserList14,omitempty"`

	// user list15
	UserList15 int32 `json:"UserList15,omitempty"`

	// user list16
	UserList16 int32 `json:"UserList16,omitempty"`

	// user list17
	UserList17 int32 `json:"UserList17,omitempty"`

	// user list18
	UserList18 int32 `json:"UserList18,omitempty"`

	// user list19
	UserList19 int32 `json:"UserList19,omitempty"`

	// user list2
	UserList2 int32 `json:"UserList2,omitempty"`

	// user list20
	UserList20 int32 `json:"UserList20,omitempty"`

	// user list21
	UserList21 int32 `json:"UserList21,omitempty"`

	// user list22
	UserList22 int32 `json:"UserList22,omitempty"`

	// user list23
	UserList23 int32 `json:"UserList23,omitempty"`

	// user list24
	UserList24 int32 `json:"UserList24,omitempty"`

	// user list25
	UserList25 int32 `json:"UserList25,omitempty"`

	// user list26
	UserList26 int32 `json:"UserList26,omitempty"`

	// user list27
	UserList27 int32 `json:"UserList27,omitempty"`

	// user list28
	UserList28 int32 `json:"UserList28,omitempty"`

	// user list29
	UserList29 int32 `json:"UserList29,omitempty"`

	// user list3
	UserList3 int32 `json:"UserList3,omitempty"`

	// user list30
	UserList30 int32 `json:"UserList30,omitempty"`

	// user list4
	UserList4 int32 `json:"UserList4,omitempty"`

	// user list5
	UserList5 int32 `json:"UserList5,omitempty"`

	// user list6
	UserList6 int32 `json:"UserList6,omitempty"`

	// user list7
	UserList7 int32 `json:"UserList7,omitempty"`

	// user list8
	UserList8 int32 `json:"UserList8,omitempty"`

	// user list9
	UserList9 int32 `json:"UserList9,omitempty"`

	// user number1
	UserNumber1 float64 `json:"UserNumber1,omitempty"`

	// user number10
	UserNumber10 float64 `json:"UserNumber10,omitempty"`

	// user number11
	UserNumber11 float64 `json:"UserNumber11,omitempty"`

	// user number12
	UserNumber12 float64 `json:"UserNumber12,omitempty"`

	// user number13
	UserNumber13 float64 `json:"UserNumber13,omitempty"`

	// user number14
	UserNumber14 float64 `json:"UserNumber14,omitempty"`

	// user number15
	UserNumber15 float64 `json:"UserNumber15,omitempty"`

	// user number16
	UserNumber16 float64 `json:"UserNumber16,omitempty"`

	// user number17
	UserNumber17 float64 `json:"UserNumber17,omitempty"`

	// user number18
	UserNumber18 float64 `json:"UserNumber18,omitempty"`

	// user number19
	UserNumber19 float64 `json:"UserNumber19,omitempty"`

	// user number2
	UserNumber2 float64 `json:"UserNumber2,omitempty"`

	// user number20
	UserNumber20 float64 `json:"UserNumber20,omitempty"`

	// user number21
	UserNumber21 float64 `json:"UserNumber21,omitempty"`

	// user number22
	UserNumber22 float64 `json:"UserNumber22,omitempty"`

	// user number23
	UserNumber23 float64 `json:"UserNumber23,omitempty"`

	// user number24
	UserNumber24 float64 `json:"UserNumber24,omitempty"`

	// user number25
	UserNumber25 float64 `json:"UserNumber25,omitempty"`

	// user number26
	UserNumber26 float64 `json:"UserNumber26,omitempty"`

	// user number27
	UserNumber27 float64 `json:"UserNumber27,omitempty"`

	// user number28
	UserNumber28 float64 `json:"UserNumber28,omitempty"`

	// user number29
	UserNumber29 float64 `json:"UserNumber29,omitempty"`

	// user number3
	UserNumber3 float64 `json:"UserNumber3,omitempty"`

	// user number30
	UserNumber30 float64 `json:"UserNumber30,omitempty"`

	// user number4
	UserNumber4 float64 `json:"UserNumber4,omitempty"`

	// user number5
	UserNumber5 float64 `json:"UserNumber5,omitempty"`

	// user number6
	UserNumber6 float64 `json:"UserNumber6,omitempty"`

	// user number7
	UserNumber7 float64 `json:"UserNumber7,omitempty"`

	// user number8
	UserNumber8 float64 `json:"UserNumber8,omitempty"`

	// user number9
	UserNumber9 float64 `json:"UserNumber9,omitempty"`

	// user text1
	UserText1 string `json:"UserText1,omitempty"`

	// user text10
	UserText10 string `json:"UserText10,omitempty"`

	// user text11
	UserText11 string `json:"UserText11,omitempty"`

	// user text12
	UserText12 string `json:"UserText12,omitempty"`

	// user text13
	UserText13 string `json:"UserText13,omitempty"`

	// user text14
	UserText14 string `json:"UserText14,omitempty"`

	// user text15
	UserText15 string `json:"UserText15,omitempty"`

	// user text16
	UserText16 string `json:"UserText16,omitempty"`

	// user text17
	UserText17 string `json:"UserText17,omitempty"`

	// user text18
	UserText18 string `json:"UserText18,omitempty"`

	// user text19
	UserText19 string `json:"UserText19,omitempty"`

	// user text2
	UserText2 string `json:"UserText2,omitempty"`

	// user text20
	UserText20 string `json:"UserText20,omitempty"`

	// user text21
	UserText21 string `json:"UserText21,omitempty"`

	// user text22
	UserText22 string `json:"UserText22,omitempty"`

	// user text23
	UserText23 string `json:"UserText23,omitempty"`

	// user text24
	UserText24 string `json:"UserText24,omitempty"`

	// user text25
	UserText25 string `json:"UserText25,omitempty"`

	// user text26
	UserText26 string `json:"UserText26,omitempty"`

	// user text27
	UserText27 string `json:"UserText27,omitempty"`

	// user text28
	UserText28 string `json:"UserText28,omitempty"`

	// user text29
	UserText29 string `json:"UserText29,omitempty"`

	// user text3
	UserText3 string `json:"UserText3,omitempty"`

	// user text30
	UserText30 string `json:"UserText30,omitempty"`

	// user text4
	UserText4 string `json:"UserText4,omitempty"`

	// user text5
	UserText5 string `json:"UserText5,omitempty"`

	// user text6
	UserText6 string `json:"UserText6,omitempty"`

	// user text7
	UserText7 string `json:"UserText7,omitempty"`

	// user text8
	UserText8 string `json:"UserText8,omitempty"`

	// user text9
	UserText9 string `json:"UserText9,omitempty"`

	// warrantor
	Warrantor string `json:"Warrantor,omitempty"`

	// warranty expiry
	WarrantyExpiry *ConquestAPITimestampValue `json:"WarrantyExpiry,omitempty"`

	// year created
	YearCreated *ConquestAPITimestampValue `json:"YearCreated,omitempty"`
}

// Validate validates this conquest api asset record
func (m *ConquestAPIAssetRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateAcquired(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGeometryData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocationCoordinates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRenewBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSysUserDate1(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSysUserDate2(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate1(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate10(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate11(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate12(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate13(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate14(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate15(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate16(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate17(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate18(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate19(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate2(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate20(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate21(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate22(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate23(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate24(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate25(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate26(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate27(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate28(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate29(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate3(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate30(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate4(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate5(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate6(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate7(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate8(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserDate9(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarrantyExpiry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYearCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIAssetRecord) validateDateAcquired(formats strfmt.Registry) error {
	if swag.IsZero(m.DateAcquired) { // not required
		return nil
	}

	if m.DateAcquired != nil {
		if err := m.DateAcquired.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("DateAcquired")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("DateAcquired")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateExpiry(formats strfmt.Registry) error {
	if swag.IsZero(m.Expiry) { // not required
		return nil
	}

	if m.Expiry != nil {
		if err := m.Expiry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Expiry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Expiry")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateGeometryData(formats strfmt.Registry) error {
	if swag.IsZero(m.GeometryData) { // not required
		return nil
	}

	if m.GeometryData != nil {
		if err := m.GeometryData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeometryData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("GeometryData")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateLocationCoordinates(formats strfmt.Registry) error {
	if swag.IsZero(m.LocationCoordinates) { // not required
		return nil
	}

	if m.LocationCoordinates != nil {
		if err := m.LocationCoordinates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("LocationCoordinates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("LocationCoordinates")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateRenewBy(formats strfmt.Registry) error {
	if swag.IsZero(m.RenewBy) { // not required
		return nil
	}

	if m.RenewBy != nil {
		if err := m.RenewBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("RenewBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("RenewBy")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateSysUserDate1(formats strfmt.Registry) error {
	if swag.IsZero(m.SysUserDate1) { // not required
		return nil
	}

	if m.SysUserDate1 != nil {
		if err := m.SysUserDate1.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SysUserDate1")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("SysUserDate1")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateSysUserDate2(formats strfmt.Registry) error {
	if swag.IsZero(m.SysUserDate2) { // not required
		return nil
	}

	if m.SysUserDate2 != nil {
		if err := m.SysUserDate2.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SysUserDate2")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("SysUserDate2")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate1(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate1) { // not required
		return nil
	}

	if m.UserDate1 != nil {
		if err := m.UserDate1.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate1")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate1")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate10(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate10) { // not required
		return nil
	}

	if m.UserDate10 != nil {
		if err := m.UserDate10.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate10")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate10")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate11(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate11) { // not required
		return nil
	}

	if m.UserDate11 != nil {
		if err := m.UserDate11.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate11")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate11")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate12(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate12) { // not required
		return nil
	}

	if m.UserDate12 != nil {
		if err := m.UserDate12.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate12")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate12")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate13(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate13) { // not required
		return nil
	}

	if m.UserDate13 != nil {
		if err := m.UserDate13.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate13")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate13")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate14(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate14) { // not required
		return nil
	}

	if m.UserDate14 != nil {
		if err := m.UserDate14.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate14")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate14")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate15(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate15) { // not required
		return nil
	}

	if m.UserDate15 != nil {
		if err := m.UserDate15.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate15")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate15")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate16(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate16) { // not required
		return nil
	}

	if m.UserDate16 != nil {
		if err := m.UserDate16.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate16")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate16")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate17(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate17) { // not required
		return nil
	}

	if m.UserDate17 != nil {
		if err := m.UserDate17.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate17")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate17")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate18(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate18) { // not required
		return nil
	}

	if m.UserDate18 != nil {
		if err := m.UserDate18.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate18")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate18")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate19(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate19) { // not required
		return nil
	}

	if m.UserDate19 != nil {
		if err := m.UserDate19.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate19")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate19")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate2(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate2) { // not required
		return nil
	}

	if m.UserDate2 != nil {
		if err := m.UserDate2.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate2")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate2")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate20(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate20) { // not required
		return nil
	}

	if m.UserDate20 != nil {
		if err := m.UserDate20.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate20")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate20")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate21(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate21) { // not required
		return nil
	}

	if m.UserDate21 != nil {
		if err := m.UserDate21.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate21")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate21")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate22(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate22) { // not required
		return nil
	}

	if m.UserDate22 != nil {
		if err := m.UserDate22.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate22")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate22")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate23(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate23) { // not required
		return nil
	}

	if m.UserDate23 != nil {
		if err := m.UserDate23.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate23")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate23")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate24(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate24) { // not required
		return nil
	}

	if m.UserDate24 != nil {
		if err := m.UserDate24.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate24")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate24")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate25(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate25) { // not required
		return nil
	}

	if m.UserDate25 != nil {
		if err := m.UserDate25.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate25")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate25")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate26(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate26) { // not required
		return nil
	}

	if m.UserDate26 != nil {
		if err := m.UserDate26.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate26")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate26")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate27(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate27) { // not required
		return nil
	}

	if m.UserDate27 != nil {
		if err := m.UserDate27.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate27")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate27")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate28(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate28) { // not required
		return nil
	}

	if m.UserDate28 != nil {
		if err := m.UserDate28.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate28")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate28")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate29(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate29) { // not required
		return nil
	}

	if m.UserDate29 != nil {
		if err := m.UserDate29.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate29")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate29")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate3(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate3) { // not required
		return nil
	}

	if m.UserDate3 != nil {
		if err := m.UserDate3.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate3")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate3")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate30(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate30) { // not required
		return nil
	}

	if m.UserDate30 != nil {
		if err := m.UserDate30.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate30")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate30")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate4(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate4) { // not required
		return nil
	}

	if m.UserDate4 != nil {
		if err := m.UserDate4.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate4")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate4")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate5(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate5) { // not required
		return nil
	}

	if m.UserDate5 != nil {
		if err := m.UserDate5.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate5")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate5")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate6(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate6) { // not required
		return nil
	}

	if m.UserDate6 != nil {
		if err := m.UserDate6.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate6")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate6")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate7(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate7) { // not required
		return nil
	}

	if m.UserDate7 != nil {
		if err := m.UserDate7.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate7")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate7")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate8(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate8) { // not required
		return nil
	}

	if m.UserDate8 != nil {
		if err := m.UserDate8.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate8")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate8")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateUserDate9(formats strfmt.Registry) error {
	if swag.IsZero(m.UserDate9) { // not required
		return nil
	}

	if m.UserDate9 != nil {
		if err := m.UserDate9.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate9")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate9")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateWarrantyExpiry(formats strfmt.Registry) error {
	if swag.IsZero(m.WarrantyExpiry) { // not required
		return nil
	}

	if m.WarrantyExpiry != nil {
		if err := m.WarrantyExpiry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("WarrantyExpiry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("WarrantyExpiry")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) validateYearCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.YearCreated) { // not required
		return nil
	}

	if m.YearCreated != nil {
		if err := m.YearCreated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("YearCreated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("YearCreated")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this conquest api asset record based on the context it is used
func (m *ConquestAPIAssetRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDateAcquired(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExpiry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGeometryData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLocationCoordinates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRenewBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSysUserDate1(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSysUserDate2(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate1(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate10(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate11(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate12(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate13(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate14(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate15(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate16(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate17(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate18(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate19(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate2(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate20(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate21(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate22(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate23(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate24(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate25(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate26(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate27(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate28(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate29(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate3(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate30(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate4(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate5(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate6(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate7(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate8(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserDate9(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWarrantyExpiry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateYearCreated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateDateAcquired(ctx context.Context, formats strfmt.Registry) error {

	if m.DateAcquired != nil {
		if err := m.DateAcquired.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("DateAcquired")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("DateAcquired")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateExpiry(ctx context.Context, formats strfmt.Registry) error {

	if m.Expiry != nil {
		if err := m.Expiry.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Expiry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Expiry")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateGeometryData(ctx context.Context, formats strfmt.Registry) error {

	if m.GeometryData != nil {
		if err := m.GeometryData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeometryData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("GeometryData")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateLocationCoordinates(ctx context.Context, formats strfmt.Registry) error {

	if m.LocationCoordinates != nil {
		if err := m.LocationCoordinates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("LocationCoordinates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("LocationCoordinates")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateRenewBy(ctx context.Context, formats strfmt.Registry) error {

	if m.RenewBy != nil {
		if err := m.RenewBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("RenewBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("RenewBy")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateSysUserDate1(ctx context.Context, formats strfmt.Registry) error {

	if m.SysUserDate1 != nil {
		if err := m.SysUserDate1.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SysUserDate1")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("SysUserDate1")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateSysUserDate2(ctx context.Context, formats strfmt.Registry) error {

	if m.SysUserDate2 != nil {
		if err := m.SysUserDate2.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SysUserDate2")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("SysUserDate2")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate1(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate1 != nil {
		if err := m.UserDate1.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate1")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate1")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate10(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate10 != nil {
		if err := m.UserDate10.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate10")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate10")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate11(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate11 != nil {
		if err := m.UserDate11.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate11")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate11")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate12(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate12 != nil {
		if err := m.UserDate12.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate12")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate12")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate13(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate13 != nil {
		if err := m.UserDate13.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate13")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate13")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate14(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate14 != nil {
		if err := m.UserDate14.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate14")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate14")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate15(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate15 != nil {
		if err := m.UserDate15.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate15")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate15")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate16(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate16 != nil {
		if err := m.UserDate16.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate16")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate16")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate17(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate17 != nil {
		if err := m.UserDate17.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate17")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate17")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate18(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate18 != nil {
		if err := m.UserDate18.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate18")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate18")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate19(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate19 != nil {
		if err := m.UserDate19.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate19")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate19")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate2(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate2 != nil {
		if err := m.UserDate2.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate2")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate2")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate20(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate20 != nil {
		if err := m.UserDate20.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate20")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate20")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate21(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate21 != nil {
		if err := m.UserDate21.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate21")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate21")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate22(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate22 != nil {
		if err := m.UserDate22.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate22")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate22")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate23(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate23 != nil {
		if err := m.UserDate23.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate23")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate23")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate24(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate24 != nil {
		if err := m.UserDate24.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate24")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate24")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate25(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate25 != nil {
		if err := m.UserDate25.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate25")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate25")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate26(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate26 != nil {
		if err := m.UserDate26.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate26")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate26")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate27(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate27 != nil {
		if err := m.UserDate27.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate27")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate27")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate28(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate28 != nil {
		if err := m.UserDate28.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate28")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate28")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate29(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate29 != nil {
		if err := m.UserDate29.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate29")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate29")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate3(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate3 != nil {
		if err := m.UserDate3.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate3")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate3")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate30(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate30 != nil {
		if err := m.UserDate30.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate30")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate30")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate4(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate4 != nil {
		if err := m.UserDate4.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate4")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate4")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate5(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate5 != nil {
		if err := m.UserDate5.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate5")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate5")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate6(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate6 != nil {
		if err := m.UserDate6.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate6")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate6")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate7(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate7 != nil {
		if err := m.UserDate7.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate7")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate7")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate8(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate8 != nil {
		if err := m.UserDate8.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate8")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate8")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateUserDate9(ctx context.Context, formats strfmt.Registry) error {

	if m.UserDate9 != nil {
		if err := m.UserDate9.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserDate9")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserDate9")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateWarrantyExpiry(ctx context.Context, formats strfmt.Registry) error {

	if m.WarrantyExpiry != nil {
		if err := m.WarrantyExpiry.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("WarrantyExpiry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("WarrantyExpiry")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIAssetRecord) contextValidateYearCreated(ctx context.Context, formats strfmt.Registry) error {

	if m.YearCreated != nil {
		if err := m.YearCreated.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("YearCreated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("YearCreated")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIAssetRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIAssetRecord) UnmarshalBinary(b []byte) error {
	var res ConquestAPIAssetRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
