// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIUserViewFilter conquest api user view filter
//
// swagger:model conquest_apiUserViewFilter
type ConquestAPIUserViewFilter struct {

	// description
	Description string `json:"Description,omitempty"`

	// filter ID
	FilterID int32 `json:"FilterID,omitempty"`

	// filter name
	FilterName string `json:"FilterName,omitempty"`
}

// Validate validates this conquest api user view filter
func (m *ConquestAPIUserViewFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api user view filter based on context it is used
func (m *ConquestAPIUserViewFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIUserViewFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIUserViewFilter) UnmarshalBinary(b []byte) error {
	var res ConquestAPIUserViewFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
