// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIConfigLeafletMapConnection conquest api config leaflet map connection
//
// swagger:model conquest_api_configLeafletMapConnection
type ConquestAPIConfigLeafletMapConnection struct {

	// access key
	AccessKey string `json:"access_key,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// max zoom
	MaxZoom float64 `json:"max_zoom,omitempty"`

	// min zoom
	MinZoom float64 `json:"min_zoom,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`

	// template url
	TemplateURL string `json:"template_url,omitempty"`
}

// Validate validates this conquest api config leaflet map connection
func (m *ConquestAPIConfigLeafletMapConnection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api config leaflet map connection based on context it is used
func (m *ConquestAPIConfigLeafletMapConnection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIConfigLeafletMapConnection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIConfigLeafletMapConnection) UnmarshalBinary(b []byte) error {
	var res ConquestAPIConfigLeafletMapConnection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
