// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIReport conquest api report
//
// swagger:model conquest_apiReport
type ConquestAPIReport struct {

	// ReportDefinition is used on the server side to get the required report document.
	// This is the key
	ReportDefinition string `json:"ReportDefinition,omitempty"`

	// ReportName is used to display the name of the report on client side
	ReportName string `json:"ReportName,omitempty"`
}

// Validate validates this conquest api report
func (m *ConquestAPIReport) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api report based on context it is used
func (m *ConquestAPIReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIReport) UnmarshalBinary(b []byte) error {
	var res ConquestAPIReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
