// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPICreateAssetCommand conquest api create asset command
//
// swagger:model conquest_apiCreateAssetCommand
type ConquestAPICreateAssetCommand struct {

	// asset description
	AssetDescription string `json:"AssetDescription,omitempty"`

	// ParentID is 0 if this is a Facility
	ParentID int32 `json:"ParentID,omitempty"`

	// proposed
	Proposed bool `json:"Proposed,omitempty"`

	// type ID
	TypeID int32 `json:"TypeID,omitempty"`
}

// Validate validates this conquest api create asset command
func (m *ConquestAPICreateAssetCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPICreateAssetCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPICreateAssetCommand) UnmarshalBinary(b []byte) error {
	var res ConquestAPICreateAssetCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
