// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestApigpkgContents conquest apigpkg contents
//
// swagger:model conquest_apigpkg_contents
type ConquestApigpkgContents struct {

	// data type
	DataType string `json:"data_type,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// last change
	// Format: date-time
	LastChange strfmt.DateTime `json:"last_change,omitempty"`

	// max x
	Maxx float64 `json:"max_x,omitempty"`

	// max y
	Maxy float64 `json:"max_y,omitempty"`

	// min x
	Minx float64 `json:"min_x,omitempty"`

	// min y
	Miny float64 `json:"min_y,omitempty"`

	// srs id
	SrsID int32 `json:"srs_id,omitempty"`

	// table name
	TableName string `json:"table_name,omitempty"`
}

// Validate validates this conquest apigpkg contents
func (m *ConquestApigpkgContents) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastChange(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestApigpkgContents) validateLastChange(formats strfmt.Registry) error {
	if swag.IsZero(m.LastChange) { // not required
		return nil
	}

	if err := validate.FormatOf("last_change", "body", "date-time", m.LastChange.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this conquest apigpkg contents based on context it is used
func (m *ConquestApigpkgContents) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestApigpkgContents) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestApigpkgContents) UnmarshalBinary(b []byte) error {
	var res ConquestApigpkgContents
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
