// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPICreateDefectForAssetCommand conquest api create defect for asset command
//
// swagger:model conquest_apiCreateDefectForAssetCommand
type ConquestAPICreateDefectForAssetCommand struct {

	// asset ID
	AssetID int32 `json:"AssetID,omitempty"`

	// std defect ID
	StdDefectID int32 `json:"StdDefectID,omitempty"`
}

// Validate validates this conquest api create defect for asset command
func (m *ConquestAPICreateDefectForAssetCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api create defect for asset command based on context it is used
func (m *ConquestAPICreateDefectForAssetCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPICreateDefectForAssetCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPICreateDefectForAssetCommand) UnmarshalBinary(b []byte) error {
	var res ConquestAPICreateDefectForAssetCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
