// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestAPIMasterActionCompletionProcess conquest api master action completion process
//
// swagger:model conquest_apiMasterActionCompletionProcess
type ConquestAPIMasterActionCompletionProcess struct {

	// create master for repeatable sub actions
	CreateMasterForRepeatableSubActions bool `json:"CreateMasterForRepeatableSubActions,omitempty"`

	// next repeatable date
	// Format: date-time
	NextRepeatableDate strfmt.DateTime `json:"NextRepeatableDate,omitempty"`
}

// Validate validates this conquest api master action completion process
func (m *ConquestAPIMasterActionCompletionProcess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextRepeatableDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIMasterActionCompletionProcess) validateNextRepeatableDate(formats strfmt.Registry) error {
	if swag.IsZero(m.NextRepeatableDate) { // not required
		return nil
	}

	if err := validate.FormatOf("NextRepeatableDate", "body", "date-time", m.NextRepeatableDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this conquest api master action completion process based on context it is used
func (m *ConquestAPIMasterActionCompletionProcess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIMasterActionCompletionProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIMasterActionCompletionProcess) UnmarshalBinary(b []byte) error {
	var res ConquestAPIMasterActionCompletionProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
