// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIChangeAssetTypeCommand conquest api change asset type command
//
// swagger:model conquest_apiChangeAssetTypeCommand
type ConquestAPIChangeAssetTypeCommand struct {

	// asset ID
	AssetID int32 `json:"AssetID,omitempty"`

	// expiry date
	ExpiryDate *ConquestAPITimestampValue `json:"ExpiryDate,omitempty"`

	// original type ID
	OriginalTypeID int32 `json:"OriginalTypeID,omitempty"`

	// transaction date
	TransactionDate *ConquestAPITimestampValue `json:"TransactionDate,omitempty"`

	// type ID
	TypeID int32 `json:"TypeID,omitempty"`
}

// Validate validates this conquest api change asset type command
func (m *ConquestAPIChangeAssetTypeCommand) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiryDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIChangeAssetTypeCommand) validateExpiryDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiryDate) { // not required
		return nil
	}

	if m.ExpiryDate != nil {
		if err := m.ExpiryDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ExpiryDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ExpiryDate")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIChangeAssetTypeCommand) validateTransactionDate(formats strfmt.Registry) error {
	if swag.IsZero(m.TransactionDate) { // not required
		return nil
	}

	if m.TransactionDate != nil {
		if err := m.TransactionDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("TransactionDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("TransactionDate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this conquest api change asset type command based on the context it is used
func (m *ConquestAPIChangeAssetTypeCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExpiryDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIChangeAssetTypeCommand) contextValidateExpiryDate(ctx context.Context, formats strfmt.Registry) error {

	if m.ExpiryDate != nil {
		if err := m.ExpiryDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ExpiryDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ExpiryDate")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIChangeAssetTypeCommand) contextValidateTransactionDate(ctx context.Context, formats strfmt.Registry) error {

	if m.TransactionDate != nil {
		if err := m.TransactionDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("TransactionDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("TransactionDate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIChangeAssetTypeCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIChangeAssetTypeCommand) UnmarshalBinary(b []byte) error {
	var res ConquestAPIChangeAssetTypeCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
