// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIResponseTimeData conquest api response time data
//
// swagger:model conquest_apiResponseTimeData
type ConquestAPIResponseTimeData struct {

	// priority ID
	PriorityID int32 `json:"PriorityID,omitempty"`

	// respond in
	RespondIn int32 `json:"RespondIn,omitempty"`

	// score
	Score float64 `json:"Score,omitempty"`

	// unit type ID
	UnitTypeID int32 `json:"UnitTypeID,omitempty"`
}

// Validate validates this conquest api response time data
func (m *ConquestAPIResponseTimeData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api response time data based on context it is used
func (m *ConquestAPIResponseTimeData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIResponseTimeData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIResponseTimeData) UnmarshalBinary(b []byte) error {
	var res ConquestAPIResponseTimeData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
