// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ConquestAPIConfigBlobStoreMode - BlobStoreMode_Redirect: Clients will receive and be redirected to the blob location
//  - BlobStoreMode_Gateway: Clients will download and upload from the blob location, via the API
//
// swagger:model conquest_api_configBlobStoreMode
type ConquestAPIConfigBlobStoreMode string

const (

	// ConquestAPIConfigBlobStoreModeBlobStoreModeRedirect captures enum value "BlobStoreMode_Redirect"
	ConquestAPIConfigBlobStoreModeBlobStoreModeRedirect ConquestAPIConfigBlobStoreMode = "BlobStoreMode_Redirect"

	// ConquestAPIConfigBlobStoreModeBlobStoreModeGateway captures enum value "BlobStoreMode_Gateway"
	ConquestAPIConfigBlobStoreModeBlobStoreModeGateway ConquestAPIConfigBlobStoreMode = "BlobStoreMode_Gateway"
)

// for schema
var conquestApiConfigBlobStoreModeEnum []interface{}

func init() {
	var res []ConquestAPIConfigBlobStoreMode
	if err := json.Unmarshal([]byte(`["BlobStoreMode_Redirect","BlobStoreMode_Gateway"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		conquestApiConfigBlobStoreModeEnum = append(conquestApiConfigBlobStoreModeEnum, v)
	}
}

func (m ConquestAPIConfigBlobStoreMode) validateConquestAPIConfigBlobStoreModeEnum(path, location string, value ConquestAPIConfigBlobStoreMode) error {
	if err := validate.Enum(path, location, value, conquestApiConfigBlobStoreModeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this conquest api config blob store mode
func (m ConquestAPIConfigBlobStoreMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConquestAPIConfigBlobStoreModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
