// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ConquestAPIObjectAttributeKind conquest api object attribute kind
//
// swagger:model conquest_apiObjectAttributeKind
type ConquestAPIObjectAttributeKind string

func NewConquestAPIObjectAttributeKind(value ConquestAPIObjectAttributeKind) *ConquestAPIObjectAttributeKind {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ConquestAPIObjectAttributeKind.
func (m ConquestAPIObjectAttributeKind) Pointer() *ConquestAPIObjectAttributeKind {
	return &m
}

const (

	// ConquestAPIObjectAttributeKindObjectAttributeKindValue captures enum value "ObjectAttributeKind_Value"
	ConquestAPIObjectAttributeKindObjectAttributeKindValue ConquestAPIObjectAttributeKind = "ObjectAttributeKind_Value"

	// ConquestAPIObjectAttributeKindObjectAttributeKindCalculated captures enum value "ObjectAttributeKind_Calculated"
	ConquestAPIObjectAttributeKindObjectAttributeKindCalculated ConquestAPIObjectAttributeKind = "ObjectAttributeKind_Calculated"
)

// for schema
var conquestApiObjectAttributeKindEnum []interface{}

func init() {
	var res []ConquestAPIObjectAttributeKind
	if err := json.Unmarshal([]byte(`["ObjectAttributeKind_Value","ObjectAttributeKind_Calculated"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		conquestApiObjectAttributeKindEnum = append(conquestApiObjectAttributeKindEnum, v)
	}
}

func (m ConquestAPIObjectAttributeKind) validateConquestAPIObjectAttributeKindEnum(path, location string, value ConquestAPIObjectAttributeKind) error {
	if err := validate.EnumCase(path, location, value, conquestApiObjectAttributeKindEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this conquest api object attribute kind
func (m ConquestAPIObjectAttributeKind) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConquestAPIObjectAttributeKindEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this conquest api object attribute kind based on context it is used
func (m ConquestAPIObjectAttributeKind) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
