// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestAPIRequestRecordChangeSet conquest api request record change set
//
// swagger:model conquest_apiRequestRecordChangeSet
type ConquestAPIRequestRecordChangeSet struct {

	// changes
	Changes []string `json:"Changes"`

	// last edit
	// Format: date-time
	LastEdit strfmt.DateTime `json:"LastEdit,omitempty"`

	// original
	Original *ConquestAPIRequestRecord `json:"Original,omitempty"`

	// request ID
	RequestID int32 `json:"RequestID,omitempty"`

	// updated
	Updated *ConquestAPIRequestRecord `json:"Updated,omitempty"`
}

// Validate validates this conquest api request record change set
func (m *ConquestAPIRequestRecordChangeSet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastEdit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIRequestRecordChangeSet) validateLastEdit(formats strfmt.Registry) error {

	if swag.IsZero(m.LastEdit) { // not required
		return nil
	}

	if err := validate.FormatOf("LastEdit", "body", "date-time", m.LastEdit.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ConquestAPIRequestRecordChangeSet) validateOriginal(formats strfmt.Registry) error {

	if swag.IsZero(m.Original) { // not required
		return nil
	}

	if m.Original != nil {
		if err := m.Original.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Original")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIRequestRecordChangeSet) validateUpdated(formats strfmt.Registry) error {

	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if m.Updated != nil {
		if err := m.Updated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Updated")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIRequestRecordChangeSet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIRequestRecordChangeSet) UnmarshalBinary(b []byte) error {
	var res ConquestAPIRequestRecordChangeSet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
