// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPILock conquest api lock
//
// swagger:model conquest_apiLock
type ConquestAPILock struct {

	// for an Asset, 'Read Only' or 'Disposed'
	// for an Action, 'Read Only', 'At Issue', ..., 'Completed'
	// for a Defect 'Read Only', 'Completed'
	Status []string `json:"Status"`
}

// Validate validates this conquest api lock
func (m *ConquestAPILock) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conquest api lock based on context it is used
func (m *ConquestAPILock) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPILock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPILock) UnmarshalBinary(b []byte) error {
	var res ConquestAPILock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
