// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIJobState conquest api job state
//
// swagger:model conquest_apiJobState
type ConquestAPIJobState struct {

	// creation_details for when this job was submitted.
	CreationDetails *ConquestAPIJobCreationDetails `json:"creation_details,omitempty"`

	// job key
	JobKey *ConquestAPIJobKey `json:"job_key,omitempty"`

	// The progress of the job. This changes during the lifecycle of the job.
	Progress *ConquestAPIJobProgressInfo `json:"progress,omitempty"`

	// JobResult is set after the job has ended, that is, when the status is one of
	// [JobStatus_Invalid, JobStatus_Completed, JobStatus_CompletedWithError]
	Result *ConquestAPIJobResult `json:"result,omitempty"`
}

// Validate validates this conquest api job state
func (m *ConquestAPIJobState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProgress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIJobState) validateCreationDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.CreationDetails) { // not required
		return nil
	}

	if m.CreationDetails != nil {
		if err := m.CreationDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creation_details")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIJobState) validateJobKey(formats strfmt.Registry) error {

	if swag.IsZero(m.JobKey) { // not required
		return nil
	}

	if m.JobKey != nil {
		if err := m.JobKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("job_key")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIJobState) validateProgress(formats strfmt.Registry) error {

	if swag.IsZero(m.Progress) { // not required
		return nil
	}

	if m.Progress != nil {
		if err := m.Progress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("progress")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIJobState) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(m.Result) { // not required
		return nil
	}

	if m.Result != nil {
		if err := m.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIJobState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIJobState) UnmarshalBinary(b []byte) error {
	var res ConquestAPIJobState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
