// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestAPIUpdateCodeListRecordChangeSet conquest api update code list record change set
//
// swagger:model conquest_apiUpdateCodeListRecordChangeSet
type ConquestAPIUpdateCodeListRecordChangeSet struct {

	// changes
	Changes []string `json:"Changes"`

	// code list ID
	CodeListID int32 `json:"CodeListID,omitempty"`

	// last edit
	// Format: date-time
	LastEdit strfmt.DateTime `json:"LastEdit,omitempty"`

	// original
	Original *ConquestAPICodeListRecord `json:"Original,omitempty"`

	// updated
	Updated *ConquestAPICodeListRecord `json:"Updated,omitempty"`
}

// Validate validates this conquest api update code list record change set
func (m *ConquestAPIUpdateCodeListRecordChangeSet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastEdit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIUpdateCodeListRecordChangeSet) validateLastEdit(formats strfmt.Registry) error {
	if swag.IsZero(m.LastEdit) { // not required
		return nil
	}

	if err := validate.FormatOf("LastEdit", "body", "date-time", m.LastEdit.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ConquestAPIUpdateCodeListRecordChangeSet) validateOriginal(formats strfmt.Registry) error {
	if swag.IsZero(m.Original) { // not required
		return nil
	}

	if m.Original != nil {
		if err := m.Original.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Original")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Original")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIUpdateCodeListRecordChangeSet) validateUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if m.Updated != nil {
		if err := m.Updated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Updated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Updated")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this conquest api update code list record change set based on the context it is used
func (m *ConquestAPIUpdateCodeListRecordChangeSet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOriginal(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPIUpdateCodeListRecordChangeSet) contextValidateOriginal(ctx context.Context, formats strfmt.Registry) error {

	if m.Original != nil {
		if err := m.Original.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Original")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Original")
			}
			return err
		}
	}

	return nil
}

func (m *ConquestAPIUpdateCodeListRecordChangeSet) contextValidateUpdated(ctx context.Context, formats strfmt.Registry) error {

	if m.Updated != nil {
		if err := m.Updated.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Updated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Updated")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIUpdateCodeListRecordChangeSet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIUpdateCodeListRecordChangeSet) UnmarshalBinary(b []byte) error {
	var res ConquestAPIUpdateCodeListRecordChangeSet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
