// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ConquestAPICompareOperator - CompareOperator_RangeInclusive: RangeComparisonType
//  - CompareOperator_Contains: SetComparisonType
//  - CompareOperator_EqualTo: ValueComparisonType
//  - CompareOperator_StringStartsWith: String comparisons
//  - CompareOperator_DescendentOf: HierarchyComparisonType
//
// swagger:model conquest_apiCompareOperator
type ConquestAPICompareOperator string

func NewConquestAPICompareOperator(value ConquestAPICompareOperator) *ConquestAPICompareOperator {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ConquestAPICompareOperator.
func (m ConquestAPICompareOperator) Pointer() *ConquestAPICompareOperator {
	return &m
}

const (

	// ConquestAPICompareOperatorCompareOperatorNone captures enum value "CompareOperator_None"
	ConquestAPICompareOperatorCompareOperatorNone ConquestAPICompareOperator = "CompareOperator_None"

	// ConquestAPICompareOperatorCompareOperatorRangeInclusive captures enum value "CompareOperator_RangeInclusive"
	ConquestAPICompareOperatorCompareOperatorRangeInclusive ConquestAPICompareOperator = "CompareOperator_RangeInclusive"

	// ConquestAPICompareOperatorCompareOperatorGreaterThan captures enum value "CompareOperator_GreaterThan"
	ConquestAPICompareOperatorCompareOperatorGreaterThan ConquestAPICompareOperator = "CompareOperator_GreaterThan"

	// ConquestAPICompareOperatorCompareOperatorGreaterThanOrEqualTo captures enum value "CompareOperator_GreaterThanOrEqualTo"
	ConquestAPICompareOperatorCompareOperatorGreaterThanOrEqualTo ConquestAPICompareOperator = "CompareOperator_GreaterThanOrEqualTo"

	// ConquestAPICompareOperatorCompareOperatorLessThan captures enum value "CompareOperator_LessThan"
	ConquestAPICompareOperatorCompareOperatorLessThan ConquestAPICompareOperator = "CompareOperator_LessThan"

	// ConquestAPICompareOperatorCompareOperatorLessThanOrEqualTo captures enum value "CompareOperator_LessThanOrEqualTo"
	ConquestAPICompareOperatorCompareOperatorLessThanOrEqualTo ConquestAPICompareOperator = "CompareOperator_LessThanOrEqualTo"

	// ConquestAPICompareOperatorCompareOperatorContains captures enum value "CompareOperator_Contains"
	ConquestAPICompareOperatorCompareOperatorContains ConquestAPICompareOperator = "CompareOperator_Contains"

	// ConquestAPICompareOperatorCompareOperatorEqualTo captures enum value "CompareOperator_EqualTo"
	ConquestAPICompareOperatorCompareOperatorEqualTo ConquestAPICompareOperator = "CompareOperator_EqualTo"

	// ConquestAPICompareOperatorCompareOperatorNotSet captures enum value "CompareOperator_NotSet"
	ConquestAPICompareOperatorCompareOperatorNotSet ConquestAPICompareOperator = "CompareOperator_NotSet"

	// ConquestAPICompareOperatorCompareOperatorStringStartsWith captures enum value "CompareOperator_StringStartsWith"
	ConquestAPICompareOperatorCompareOperatorStringStartsWith ConquestAPICompareOperator = "CompareOperator_StringStartsWith"

	// ConquestAPICompareOperatorCompareOperatorStringEndsWith captures enum value "CompareOperator_StringEndsWith"
	ConquestAPICompareOperatorCompareOperatorStringEndsWith ConquestAPICompareOperator = "CompareOperator_StringEndsWith"

	// ConquestAPICompareOperatorCompareOperatorStringContains captures enum value "CompareOperator_StringContains"
	ConquestAPICompareOperatorCompareOperatorStringContains ConquestAPICompareOperator = "CompareOperator_StringContains"

	// ConquestAPICompareOperatorCompareOperatorDescendentOf captures enum value "CompareOperator_DescendentOf"
	ConquestAPICompareOperatorCompareOperatorDescendentOf ConquestAPICompareOperator = "CompareOperator_DescendentOf"

	// ConquestAPICompareOperatorCompareOperatorAncestorOf captures enum value "CompareOperator_AncestorOf"
	ConquestAPICompareOperatorCompareOperatorAncestorOf ConquestAPICompareOperator = "CompareOperator_AncestorOf"

	// ConquestAPICompareOperatorCompareOperatorChildrenOf captures enum value "CompareOperator_ChildrenOf"
	ConquestAPICompareOperatorCompareOperatorChildrenOf ConquestAPICompareOperator = "CompareOperator_ChildrenOf"

	// ConquestAPICompareOperatorCompareOperatorContainsAnyOf captures enum value "CompareOperator_ContainsAnyOf"
	ConquestAPICompareOperatorCompareOperatorContainsAnyOf ConquestAPICompareOperator = "CompareOperator_ContainsAnyOf"
)

// for schema
var conquestApiCompareOperatorEnum []interface{}

func init() {
	var res []ConquestAPICompareOperator
	if err := json.Unmarshal([]byte(`["CompareOperator_None","CompareOperator_RangeInclusive","CompareOperator_GreaterThan","CompareOperator_GreaterThanOrEqualTo","CompareOperator_LessThan","CompareOperator_LessThanOrEqualTo","CompareOperator_Contains","CompareOperator_EqualTo","CompareOperator_NotSet","CompareOperator_StringStartsWith","CompareOperator_StringEndsWith","CompareOperator_StringContains","CompareOperator_DescendentOf","CompareOperator_AncestorOf","CompareOperator_ChildrenOf","CompareOperator_ContainsAnyOf"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		conquestApiCompareOperatorEnum = append(conquestApiCompareOperatorEnum, v)
	}
}

func (m ConquestAPICompareOperator) validateConquestAPICompareOperatorEnum(path, location string, value ConquestAPICompareOperator) error {
	if err := validate.EnumCase(path, location, value, conquestApiCompareOperatorEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this conquest api compare operator
func (m ConquestAPICompareOperator) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConquestAPICompareOperatorEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this conquest api compare operator based on context it is used
func (m ConquestAPICompareOperator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
