// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestAPISimpleActionCompletionProcess conquest api simple action completion process
//
// swagger:model conquest_apiSimpleActionCompletionProcess
type ConquestAPISimpleActionCompletionProcess struct {

	// next repeatable date
	// Format: date-time
	NextRepeatableDate strfmt.DateTime `json:"NextRepeatableDate,omitempty"`
}

// Validate validates this conquest api simple action completion process
func (m *ConquestAPISimpleActionCompletionProcess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextRepeatableDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPISimpleActionCompletionProcess) validateNextRepeatableDate(formats strfmt.Registry) error {

	if swag.IsZero(m.NextRepeatableDate) { // not required
		return nil
	}

	if err := validate.FormatOf("NextRepeatableDate", "body", "date-time", m.NextRepeatableDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPISimpleActionCompletionProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPISimpleActionCompletionProcess) UnmarshalBinary(b []byte) error {
	var res ConquestAPISimpleActionCompletionProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
