// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ConquestAPIJobType Name these in such a way that it makes that sense to call it 'X Process'
//
// - JobType_CsvImport: Csv Import
//  - JobType_CompleteActions: Action Completion
//  - ForwardPlanningDateChange: Forward Planning Date Change
//  - JobType_ConditionRecalculation: Condition Re-calculation
//  - JobType_DepreciationRecalculation: Depreciation Re-calculation
//  - JobType_IndexationUpdate: Indexation Update
//  - JobType_Revaluation: Revaluation
//  - JobType_ReplacementCostModification: Replacement Cost Modification
//  - JobType_TransactionRollback: Transaction Rollback
//  - JobType_ExpiryDateRecalculation: Expiry Date Re-calculation
//  - JobType_RiskRecalculation: Risk Score Re-calculation
//  - JobType_PostTransactions: Post Transactions
//  - JobType_Bundler: Bundler (used for zipping stuff up)
//
// swagger:model conquest_apiJobType
type ConquestAPIJobType string

const (

	// ConquestAPIJobTypeJobTypeUnknown captures enum value "JobType_Unknown"
	ConquestAPIJobTypeJobTypeUnknown ConquestAPIJobType = "JobType_Unknown"

	// ConquestAPIJobTypeJobTypeOther captures enum value "JobType_Other"
	ConquestAPIJobTypeJobTypeOther ConquestAPIJobType = "JobType_Other"

	// ConquestAPIJobTypeJobTypeCsvImport captures enum value "JobType_CsvImport"
	ConquestAPIJobTypeJobTypeCsvImport ConquestAPIJobType = "JobType_CsvImport"

	// ConquestAPIJobTypeJobTypeCompleteActions captures enum value "JobType_CompleteActions"
	ConquestAPIJobTypeJobTypeCompleteActions ConquestAPIJobType = "JobType_CompleteActions"

	// ConquestAPIJobTypeForwardPlanningDateChange captures enum value "ForwardPlanningDateChange"
	ConquestAPIJobTypeForwardPlanningDateChange ConquestAPIJobType = "ForwardPlanningDateChange"

	// ConquestAPIJobTypeJobTypeConditionRecalculation captures enum value "JobType_ConditionRecalculation"
	ConquestAPIJobTypeJobTypeConditionRecalculation ConquestAPIJobType = "JobType_ConditionRecalculation"

	// ConquestAPIJobTypeJobTypeDepreciationRecalculation captures enum value "JobType_DepreciationRecalculation"
	ConquestAPIJobTypeJobTypeDepreciationRecalculation ConquestAPIJobType = "JobType_DepreciationRecalculation"

	// ConquestAPIJobTypeJobTypeIndexationUpdate captures enum value "JobType_IndexationUpdate"
	ConquestAPIJobTypeJobTypeIndexationUpdate ConquestAPIJobType = "JobType_IndexationUpdate"

	// ConquestAPIJobTypeJobTypeRevaluation captures enum value "JobType_Revaluation"
	ConquestAPIJobTypeJobTypeRevaluation ConquestAPIJobType = "JobType_Revaluation"

	// ConquestAPIJobTypeJobTypeReplacementCostModification captures enum value "JobType_ReplacementCostModification"
	ConquestAPIJobTypeJobTypeReplacementCostModification ConquestAPIJobType = "JobType_ReplacementCostModification"

	// ConquestAPIJobTypeJobTypeTransactionRollback captures enum value "JobType_TransactionRollback"
	ConquestAPIJobTypeJobTypeTransactionRollback ConquestAPIJobType = "JobType_TransactionRollback"

	// ConquestAPIJobTypeJobTypeExpiryDateRecalculation captures enum value "JobType_ExpiryDateRecalculation"
	ConquestAPIJobTypeJobTypeExpiryDateRecalculation ConquestAPIJobType = "JobType_ExpiryDateRecalculation"

	// ConquestAPIJobTypeJobTypeRiskRecalculation captures enum value "JobType_RiskRecalculation"
	ConquestAPIJobTypeJobTypeRiskRecalculation ConquestAPIJobType = "JobType_RiskRecalculation"

	// ConquestAPIJobTypeJobTypePostTransactions captures enum value "JobType_PostTransactions"
	ConquestAPIJobTypeJobTypePostTransactions ConquestAPIJobType = "JobType_PostTransactions"

	// ConquestAPIJobTypeJobTypeBundler captures enum value "JobType_Bundler"
	ConquestAPIJobTypeJobTypeBundler ConquestAPIJobType = "JobType_Bundler"
)

// for schema
var conquestApiJobTypeEnum []interface{}

func init() {
	var res []ConquestAPIJobType
	if err := json.Unmarshal([]byte(`["JobType_Unknown","JobType_Other","JobType_CsvImport","JobType_CompleteActions","ForwardPlanningDateChange","JobType_ConditionRecalculation","JobType_DepreciationRecalculation","JobType_IndexationUpdate","JobType_Revaluation","JobType_ReplacementCostModification","JobType_TransactionRollback","JobType_ExpiryDateRecalculation","JobType_RiskRecalculation","JobType_PostTransactions","JobType_Bundler"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		conquestApiJobTypeEnum = append(conquestApiJobTypeEnum, v)
	}
}

func (m ConquestAPIJobType) validateConquestAPIJobTypeEnum(path, location string, value ConquestAPIJobType) error {
	if err := validate.Enum(path, location, value, conquestApiJobTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this conquest api job type
func (m ConquestAPIJobType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConquestAPIJobTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
