// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConquestAPICyclicActionCompletionProcess conquest api cyclic action completion process
//
// swagger:model conquest_apiCyclicActionCompletionProcess
type ConquestAPICyclicActionCompletionProcess struct {

	// next cycle due date
	// Format: date-time
	NextCycleDueDate strfmt.DateTime `json:"NextCycleDueDate,omitempty"`
}

// Validate validates this conquest api cyclic action completion process
func (m *ConquestAPICyclicActionCompletionProcess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextCycleDueDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConquestAPICyclicActionCompletionProcess) validateNextCycleDueDate(formats strfmt.Registry) error {
	if swag.IsZero(m.NextCycleDueDate) { // not required
		return nil
	}

	if err := validate.FormatOf("NextCycleDueDate", "body", "date-time", m.NextCycleDueDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this conquest api cyclic action completion process based on context it is used
func (m *ConquestAPICyclicActionCompletionProcess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPICyclicActionCompletionProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPICyclicActionCompletionProcess) UnmarshalBinary(b []byte) error {
	var res ConquestAPICyclicActionCompletionProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
