// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConquestAPIAttributeSetHierarchyValue conquest api attribute set hierarchy value
//
// swagger:model conquest_apiAttributeSet_HierarchyValue
type ConquestAPIAttributeSetHierarchyValue struct {

	// code list description
	CodeListDescription string `json:"CodeListDescription,omitempty"`

	// code list ID
	CodeListID int32 `json:"CodeListID,omitempty"`
}

// Validate validates this conquest api attribute set hierarchy value
func (m *ConquestAPIAttributeSetHierarchyValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConquestAPIAttributeSetHierarchyValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConquestAPIAttributeSetHierarchyValue) UnmarshalBinary(b []byte) error {
	var res ConquestAPIAttributeSetHierarchyValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
