// Code generated by go-swagger; DO NOT EDIT.

package defect_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// NewDefectServiceDeleteDefectParams creates a new DefectServiceDeleteDefectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDefectServiceDeleteDefectParams() *DefectServiceDeleteDefectParams {
	return &DefectServiceDeleteDefectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDefectServiceDeleteDefectParamsWithTimeout creates a new DefectServiceDeleteDefectParams object
// with the ability to set a timeout on a request.
func NewDefectServiceDeleteDefectParamsWithTimeout(timeout time.Duration) *DefectServiceDeleteDefectParams {
	return &DefectServiceDeleteDefectParams{
		timeout: timeout,
	}
}

// NewDefectServiceDeleteDefectParamsWithContext creates a new DefectServiceDeleteDefectParams object
// with the ability to set a context for a request.
func NewDefectServiceDeleteDefectParamsWithContext(ctx context.Context) *DefectServiceDeleteDefectParams {
	return &DefectServiceDeleteDefectParams{
		Context: ctx,
	}
}

// NewDefectServiceDeleteDefectParamsWithHTTPClient creates a new DefectServiceDeleteDefectParams object
// with the ability to set a custom HTTPClient for a request.
func NewDefectServiceDeleteDefectParamsWithHTTPClient(client *http.Client) *DefectServiceDeleteDefectParams {
	return &DefectServiceDeleteDefectParams{
		HTTPClient: client,
	}
}

/* DefectServiceDeleteDefectParams contains all the parameters to send to the API endpoint
   for the defect service delete defect operation.

   Typically these are written to a http.Request.
*/
type DefectServiceDeleteDefectParams struct {

	// Body.
	Body *models.ConquestAPIDeleteDefectCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the defect service delete defect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DefectServiceDeleteDefectParams) WithDefaults() *DefectServiceDeleteDefectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the defect service delete defect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DefectServiceDeleteDefectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) WithTimeout(timeout time.Duration) *DefectServiceDeleteDefectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) WithContext(ctx context.Context) *DefectServiceDeleteDefectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) WithHTTPClient(client *http.Client) *DefectServiceDeleteDefectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) WithBody(body *models.ConquestAPIDeleteDefectCommand) *DefectServiceDeleteDefectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the defect service delete defect params
func (o *DefectServiceDeleteDefectParams) SetBody(body *models.ConquestAPIDeleteDefectCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DefectServiceDeleteDefectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
