// Code generated by go-swagger; DO NOT EDIT.

package defect_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ConquestSolutions/conquest_api.examples/go-swagger/models"
)

// DefectServiceUpdateDefectReader is a Reader for the DefectServiceUpdateDefect structure.
type DefectServiceUpdateDefectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DefectServiceUpdateDefectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDefectServiceUpdateDefectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDefectServiceUpdateDefectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDefectServiceUpdateDefectOK creates a DefectServiceUpdateDefectOK with default headers values
func NewDefectServiceUpdateDefectOK() *DefectServiceUpdateDefectOK {
	return &DefectServiceUpdateDefectOK{}
}

/* DefectServiceUpdateDefectOK describes a response with status code 200, with default header values.

A successful response.
*/
type DefectServiceUpdateDefectOK struct {
	Payload *models.ConquestAPIChangeSetResult
}

func (o *DefectServiceUpdateDefectOK) Error() string {
	return fmt.Sprintf("[POST /api/defects/update_defect][%d] defectServiceUpdateDefectOK  %+v", 200, o.Payload)
}
func (o *DefectServiceUpdateDefectOK) GetPayload() *models.ConquestAPIChangeSetResult {
	return o.Payload
}

func (o *DefectServiceUpdateDefectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConquestAPIChangeSetResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDefectServiceUpdateDefectDefault creates a DefectServiceUpdateDefectDefault with default headers values
func NewDefectServiceUpdateDefectDefault(code int) *DefectServiceUpdateDefectDefault {
	return &DefectServiceUpdateDefectDefault{
		_statusCode: code,
	}
}

/* DefectServiceUpdateDefectDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DefectServiceUpdateDefectDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the defect service update defect default response
func (o *DefectServiceUpdateDefectDefault) Code() int {
	return o._statusCode
}

func (o *DefectServiceUpdateDefectDefault) Error() string {
	return fmt.Sprintf("[POST /api/defects/update_defect][%d] DefectService_UpdateDefect default  %+v", o._statusCode, o.Payload)
}
func (o *DefectServiceUpdateDefectDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DefectServiceUpdateDefectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
